// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/cs2.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

/**
 * Protobuf type {@code bragi.CS2BombPlantedState}
 */
public final class CS2BombPlantedState extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bragi.CS2BombPlantedState)
    CS2BombPlantedStateOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      CS2BombPlantedState.class.getName());
  }
  // Use CS2BombPlantedState.newBuilder() to construct.
  private CS2BombPlantedState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CS2BombPlantedState() {
    plantedByPlayerUrn_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bragi.Cs2Proto.internal_static_bragi_CS2BombPlantedState_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bragi.Cs2Proto.internal_static_bragi_CS2BombPlantedState_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bragi.CS2BombPlantedState.class, com.bragi.CS2BombPlantedState.Builder.class);
  }

  private int bitField0_;
  public static final int PLANTED_BY_PLAYER_URN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object plantedByPlayerUrn_ = "";
  /**
   * <code>string planted_by_player_urn = 1 [json_name = "plantedByPlayerUrn"];</code>
   * @return The plantedByPlayerUrn.
   */
  @java.lang.Override
  public java.lang.String getPlantedByPlayerUrn() {
    java.lang.Object ref = plantedByPlayerUrn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      plantedByPlayerUrn_ = s;
      return s;
    }
  }
  /**
   * <code>string planted_by_player_urn = 1 [json_name = "plantedByPlayerUrn"];</code>
   * @return The bytes for plantedByPlayerUrn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlantedByPlayerUrnBytes() {
    java.lang.Object ref = plantedByPlayerUrn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      plantedByPlayerUrn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITION_FIELD_NUMBER = 2;
  private com.bragi.CS2Position position_;
  /**
   * <code>.bragi.CS2Position position = 2 [json_name = "position"];</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.bragi.CS2Position position = 2 [json_name = "position"];</code>
   * @return The position.
   */
  @java.lang.Override
  public com.bragi.CS2Position getPosition() {
    return position_ == null ? com.bragi.CS2Position.getDefaultInstance() : position_;
  }
  /**
   * <code>.bragi.CS2Position position = 2 [json_name = "position"];</code>
   */
  @java.lang.Override
  public com.bragi.CS2PositionOrBuilder getPositionOrBuilder() {
    return position_ == null ? com.bragi.CS2Position.getDefaultInstance() : position_;
  }

  public static final int PLANTED_AT_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp plantedAt_;
  /**
   * <code>.google.protobuf.Timestamp planted_at = 3 [json_name = "plantedAt"];</code>
   * @return Whether the plantedAt field is set.
   */
  @java.lang.Override
  public boolean hasPlantedAt() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp planted_at = 3 [json_name = "plantedAt"];</code>
   * @return The plantedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getPlantedAt() {
    return plantedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : plantedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp planted_at = 3 [json_name = "plantedAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getPlantedAtOrBuilder() {
    return plantedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : plantedAt_;
  }

  public static final int COUNTDOWN_FIELD_NUMBER = 4;
  private com.google.protobuf.Duration countdown_;
  /**
   * <code>.google.protobuf.Duration countdown = 4 [json_name = "countdown"];</code>
   * @return Whether the countdown field is set.
   */
  @java.lang.Override
  public boolean hasCountdown() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.google.protobuf.Duration countdown = 4 [json_name = "countdown"];</code>
   * @return The countdown.
   */
  @java.lang.Override
  public com.google.protobuf.Duration getCountdown() {
    return countdown_ == null ? com.google.protobuf.Duration.getDefaultInstance() : countdown_;
  }
  /**
   * <code>.google.protobuf.Duration countdown = 4 [json_name = "countdown"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.DurationOrBuilder getCountdownOrBuilder() {
    return countdown_ == null ? com.google.protobuf.Duration.getDefaultInstance() : countdown_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(plantedByPlayerUrn_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, plantedByPlayerUrn_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getPosition());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getPlantedAt());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getCountdown());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(plantedByPlayerUrn_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, plantedByPlayerUrn_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPosition());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPlantedAt());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCountdown());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bragi.CS2BombPlantedState)) {
      return super.equals(obj);
    }
    com.bragi.CS2BombPlantedState other = (com.bragi.CS2BombPlantedState) obj;

    if (!getPlantedByPlayerUrn()
        .equals(other.getPlantedByPlayerUrn())) return false;
    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (hasPlantedAt() != other.hasPlantedAt()) return false;
    if (hasPlantedAt()) {
      if (!getPlantedAt()
          .equals(other.getPlantedAt())) return false;
    }
    if (hasCountdown() != other.hasCountdown()) return false;
    if (hasCountdown()) {
      if (!getCountdown()
          .equals(other.getCountdown())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PLANTED_BY_PLAYER_URN_FIELD_NUMBER;
    hash = (53 * hash) + getPlantedByPlayerUrn().hashCode();
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    if (hasPlantedAt()) {
      hash = (37 * hash) + PLANTED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getPlantedAt().hashCode();
    }
    if (hasCountdown()) {
      hash = (37 * hash) + COUNTDOWN_FIELD_NUMBER;
      hash = (53 * hash) + getCountdown().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bragi.CS2BombPlantedState parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.CS2BombPlantedState parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.CS2BombPlantedState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.CS2BombPlantedState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.CS2BombPlantedState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.CS2BombPlantedState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.CS2BombPlantedState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bragi.CS2BombPlantedState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bragi.CS2BombPlantedState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bragi.CS2BombPlantedState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bragi.CS2BombPlantedState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bragi.CS2BombPlantedState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bragi.CS2BombPlantedState prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bragi.CS2BombPlantedState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bragi.CS2BombPlantedState)
      com.bragi.CS2BombPlantedStateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bragi.Cs2Proto.internal_static_bragi_CS2BombPlantedState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bragi.Cs2Proto.internal_static_bragi_CS2BombPlantedState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bragi.CS2BombPlantedState.class, com.bragi.CS2BombPlantedState.Builder.class);
    }

    // Construct using com.bragi.CS2BombPlantedState.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getPositionFieldBuilder();
        getPlantedAtFieldBuilder();
        getCountdownFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      plantedByPlayerUrn_ = "";
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      plantedAt_ = null;
      if (plantedAtBuilder_ != null) {
        plantedAtBuilder_.dispose();
        plantedAtBuilder_ = null;
      }
      countdown_ = null;
      if (countdownBuilder_ != null) {
        countdownBuilder_.dispose();
        countdownBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bragi.Cs2Proto.internal_static_bragi_CS2BombPlantedState_descriptor;
    }

    @java.lang.Override
    public com.bragi.CS2BombPlantedState getDefaultInstanceForType() {
      return com.bragi.CS2BombPlantedState.getDefaultInstance();
    }

    @java.lang.Override
    public com.bragi.CS2BombPlantedState build() {
      com.bragi.CS2BombPlantedState result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bragi.CS2BombPlantedState buildPartial() {
      com.bragi.CS2BombPlantedState result = new com.bragi.CS2BombPlantedState(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bragi.CS2BombPlantedState result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.plantedByPlayerUrn_ = plantedByPlayerUrn_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.position_ = positionBuilder_ == null
            ? position_
            : positionBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.plantedAt_ = plantedAtBuilder_ == null
            ? plantedAt_
            : plantedAtBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.countdown_ = countdownBuilder_ == null
            ? countdown_
            : countdownBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bragi.CS2BombPlantedState) {
        return mergeFrom((com.bragi.CS2BombPlantedState)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bragi.CS2BombPlantedState other) {
      if (other == com.bragi.CS2BombPlantedState.getDefaultInstance()) return this;
      if (!other.getPlantedByPlayerUrn().isEmpty()) {
        plantedByPlayerUrn_ = other.plantedByPlayerUrn_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (other.hasPlantedAt()) {
        mergePlantedAt(other.getPlantedAt());
      }
      if (other.hasCountdown()) {
        mergeCountdown(other.getCountdown());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              plantedByPlayerUrn_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPositionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getPlantedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getCountdownFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object plantedByPlayerUrn_ = "";
    /**
     * <code>string planted_by_player_urn = 1 [json_name = "plantedByPlayerUrn"];</code>
     * @return The plantedByPlayerUrn.
     */
    public java.lang.String getPlantedByPlayerUrn() {
      java.lang.Object ref = plantedByPlayerUrn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        plantedByPlayerUrn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string planted_by_player_urn = 1 [json_name = "plantedByPlayerUrn"];</code>
     * @return The bytes for plantedByPlayerUrn.
     */
    public com.google.protobuf.ByteString
        getPlantedByPlayerUrnBytes() {
      java.lang.Object ref = plantedByPlayerUrn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        plantedByPlayerUrn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string planted_by_player_urn = 1 [json_name = "plantedByPlayerUrn"];</code>
     * @param value The plantedByPlayerUrn to set.
     * @return This builder for chaining.
     */
    public Builder setPlantedByPlayerUrn(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      plantedByPlayerUrn_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string planted_by_player_urn = 1 [json_name = "plantedByPlayerUrn"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPlantedByPlayerUrn() {
      plantedByPlayerUrn_ = getDefaultInstance().getPlantedByPlayerUrn();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string planted_by_player_urn = 1 [json_name = "plantedByPlayerUrn"];</code>
     * @param value The bytes for plantedByPlayerUrn to set.
     * @return This builder for chaining.
     */
    public Builder setPlantedByPlayerUrnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      plantedByPlayerUrn_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.bragi.CS2Position position_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.CS2Position, com.bragi.CS2Position.Builder, com.bragi.CS2PositionOrBuilder> positionBuilder_;
    /**
     * <code>.bragi.CS2Position position = 2 [json_name = "position"];</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.bragi.CS2Position position = 2 [json_name = "position"];</code>
     * @return The position.
     */
    public com.bragi.CS2Position getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? com.bragi.CS2Position.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.bragi.CS2Position position = 2 [json_name = "position"];</code>
     */
    public Builder setPosition(com.bragi.CS2Position value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
      } else {
        positionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.CS2Position position = 2 [json_name = "position"];</code>
     */
    public Builder setPosition(
        com.bragi.CS2Position.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.CS2Position position = 2 [json_name = "position"];</code>
     */
    public Builder mergePosition(com.bragi.CS2Position value) {
      if (positionBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          position_ != null &&
          position_ != com.bragi.CS2Position.getDefaultInstance()) {
          getPositionBuilder().mergeFrom(value);
        } else {
          position_ = value;
        }
      } else {
        positionBuilder_.mergeFrom(value);
      }
      if (position_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.bragi.CS2Position position = 2 [json_name = "position"];</code>
     */
    public Builder clearPosition() {
      bitField0_ = (bitField0_ & ~0x00000002);
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.CS2Position position = 2 [json_name = "position"];</code>
     */
    public com.bragi.CS2Position.Builder getPositionBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.bragi.CS2Position position = 2 [json_name = "position"];</code>
     */
    public com.bragi.CS2PositionOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            com.bragi.CS2Position.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.bragi.CS2Position position = 2 [json_name = "position"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.CS2Position, com.bragi.CS2Position.Builder, com.bragi.CS2PositionOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bragi.CS2Position, com.bragi.CS2Position.Builder, com.bragi.CS2PositionOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private com.google.protobuf.Timestamp plantedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> plantedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp planted_at = 3 [json_name = "plantedAt"];</code>
     * @return Whether the plantedAt field is set.
     */
    public boolean hasPlantedAt() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp planted_at = 3 [json_name = "plantedAt"];</code>
     * @return The plantedAt.
     */
    public com.google.protobuf.Timestamp getPlantedAt() {
      if (plantedAtBuilder_ == null) {
        return plantedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : plantedAt_;
      } else {
        return plantedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp planted_at = 3 [json_name = "plantedAt"];</code>
     */
    public Builder setPlantedAt(com.google.protobuf.Timestamp value) {
      if (plantedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        plantedAt_ = value;
      } else {
        plantedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp planted_at = 3 [json_name = "plantedAt"];</code>
     */
    public Builder setPlantedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (plantedAtBuilder_ == null) {
        plantedAt_ = builderForValue.build();
      } else {
        plantedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp planted_at = 3 [json_name = "plantedAt"];</code>
     */
    public Builder mergePlantedAt(com.google.protobuf.Timestamp value) {
      if (plantedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          plantedAt_ != null &&
          plantedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getPlantedAtBuilder().mergeFrom(value);
        } else {
          plantedAt_ = value;
        }
      } else {
        plantedAtBuilder_.mergeFrom(value);
      }
      if (plantedAt_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp planted_at = 3 [json_name = "plantedAt"];</code>
     */
    public Builder clearPlantedAt() {
      bitField0_ = (bitField0_ & ~0x00000004);
      plantedAt_ = null;
      if (plantedAtBuilder_ != null) {
        plantedAtBuilder_.dispose();
        plantedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp planted_at = 3 [json_name = "plantedAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getPlantedAtBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getPlantedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp planted_at = 3 [json_name = "plantedAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getPlantedAtOrBuilder() {
      if (plantedAtBuilder_ != null) {
        return plantedAtBuilder_.getMessageOrBuilder();
      } else {
        return plantedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : plantedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp planted_at = 3 [json_name = "plantedAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getPlantedAtFieldBuilder() {
      if (plantedAtBuilder_ == null) {
        plantedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getPlantedAt(),
                getParentForChildren(),
                isClean());
        plantedAt_ = null;
      }
      return plantedAtBuilder_;
    }

    private com.google.protobuf.Duration countdown_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> countdownBuilder_;
    /**
     * <code>.google.protobuf.Duration countdown = 4 [json_name = "countdown"];</code>
     * @return Whether the countdown field is set.
     */
    public boolean hasCountdown() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.Duration countdown = 4 [json_name = "countdown"];</code>
     * @return The countdown.
     */
    public com.google.protobuf.Duration getCountdown() {
      if (countdownBuilder_ == null) {
        return countdown_ == null ? com.google.protobuf.Duration.getDefaultInstance() : countdown_;
      } else {
        return countdownBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Duration countdown = 4 [json_name = "countdown"];</code>
     */
    public Builder setCountdown(com.google.protobuf.Duration value) {
      if (countdownBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        countdown_ = value;
      } else {
        countdownBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Duration countdown = 4 [json_name = "countdown"];</code>
     */
    public Builder setCountdown(
        com.google.protobuf.Duration.Builder builderForValue) {
      if (countdownBuilder_ == null) {
        countdown_ = builderForValue.build();
      } else {
        countdownBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Duration countdown = 4 [json_name = "countdown"];</code>
     */
    public Builder mergeCountdown(com.google.protobuf.Duration value) {
      if (countdownBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          countdown_ != null &&
          countdown_ != com.google.protobuf.Duration.getDefaultInstance()) {
          getCountdownBuilder().mergeFrom(value);
        } else {
          countdown_ = value;
        }
      } else {
        countdownBuilder_.mergeFrom(value);
      }
      if (countdown_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Duration countdown = 4 [json_name = "countdown"];</code>
     */
    public Builder clearCountdown() {
      bitField0_ = (bitField0_ & ~0x00000008);
      countdown_ = null;
      if (countdownBuilder_ != null) {
        countdownBuilder_.dispose();
        countdownBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Duration countdown = 4 [json_name = "countdown"];</code>
     */
    public com.google.protobuf.Duration.Builder getCountdownBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getCountdownFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Duration countdown = 4 [json_name = "countdown"];</code>
     */
    public com.google.protobuf.DurationOrBuilder getCountdownOrBuilder() {
      if (countdownBuilder_ != null) {
        return countdownBuilder_.getMessageOrBuilder();
      } else {
        return countdown_ == null ?
            com.google.protobuf.Duration.getDefaultInstance() : countdown_;
      }
    }
    /**
     * <code>.google.protobuf.Duration countdown = 4 [json_name = "countdown"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
        getCountdownFieldBuilder() {
      if (countdownBuilder_ == null) {
        countdownBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                getCountdown(),
                getParentForChildren(),
                isClean());
        countdown_ = null;
      }
      return countdownBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:bragi.CS2BombPlantedState)
  }

  // @@protoc_insertion_point(class_scope:bragi.CS2BombPlantedState)
  private static final com.bragi.CS2BombPlantedState DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bragi.CS2BombPlantedState();
  }

  public static com.bragi.CS2BombPlantedState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CS2BombPlantedState>
      PARSER = new com.google.protobuf.AbstractParser<CS2BombPlantedState>() {
    @java.lang.Override
    public CS2BombPlantedState parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CS2BombPlantedState> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CS2BombPlantedState> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bragi.CS2BombPlantedState getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

