// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/cs2.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

public interface CS2RoundInfoStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bragi.CS2RoundInfoState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bragi.CS2RoundStateType round_type = 1 [json_name = "roundType"];</code>
   * @return The enum numeric value on the wire for roundType.
   */
  int getRoundTypeValue();
  /**
   * <code>.bragi.CS2RoundStateType round_type = 1 [json_name = "roundType"];</code>
   * @return The roundType.
   */
  com.bragi.CS2RoundStateType getRoundType();

  /**
   * <code>.google.protobuf.Timestamp start_time = 2 [json_name = "startTime"];</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <code>.google.protobuf.Timestamp start_time = 2 [json_name = "startTime"];</code>
   * @return The startTime.
   */
  com.google.protobuf.Timestamp getStartTime();
  /**
   * <code>.google.protobuf.Timestamp start_time = 2 [json_name = "startTime"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder();

  /**
   * <code>optional .google.protobuf.Timestamp end_time = 3 [json_name = "endTime"];</code>
   * @return Whether the endTime field is set.
   */
  boolean hasEndTime();
  /**
   * <code>optional .google.protobuf.Timestamp end_time = 3 [json_name = "endTime"];</code>
   * @return The endTime.
   */
  com.google.protobuf.Timestamp getEndTime();
  /**
   * <code>optional .google.protobuf.Timestamp end_time = 3 [json_name = "endTime"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getEndTimeOrBuilder();

  /**
   * <code>optional string winning_team_urn = 4 [json_name = "winningTeamUrn"];</code>
   * @return Whether the winningTeamUrn field is set.
   */
  boolean hasWinningTeamUrn();
  /**
   * <code>optional string winning_team_urn = 4 [json_name = "winningTeamUrn"];</code>
   * @return The winningTeamUrn.
   */
  java.lang.String getWinningTeamUrn();
  /**
   * <code>optional string winning_team_urn = 4 [json_name = "winningTeamUrn"];</code>
   * @return The bytes for winningTeamUrn.
   */
  com.google.protobuf.ByteString
      getWinningTeamUrnBytes();

  /**
   * <code>optional .bragi.CS2WinReason win_reason = 5 [json_name = "winReason"];</code>
   * @return Whether the winReason field is set.
   */
  boolean hasWinReason();
  /**
   * <code>optional .bragi.CS2WinReason win_reason = 5 [json_name = "winReason"];</code>
   * @return The enum numeric value on the wire for winReason.
   */
  int getWinReasonValue();
  /**
   * <code>optional .bragi.CS2WinReason win_reason = 5 [json_name = "winReason"];</code>
   * @return The winReason.
   */
  com.bragi.CS2WinReason getWinReason();

  /**
   * <code>optional bool home_won = 6 [json_name = "homeWon"];</code>
   * @return Whether the homeWon field is set.
   */
  boolean hasHomeWon();
  /**
   * <code>optional bool home_won = 6 [json_name = "homeWon"];</code>
   * @return The homeWon.
   */
  boolean getHomeWon();
}
