// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/cs2.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

/**
 * Protobuf type {@code bragi.CS2TeamCurrentRoundState}
 */
public final class CS2TeamCurrentRoundState extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bragi.CS2TeamCurrentRoundState)
    CS2TeamCurrentRoundStateOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      CS2TeamCurrentRoundState.class.getName());
  }
  // Use CS2TeamCurrentRoundState.newBuilder() to construct.
  private CS2TeamCurrentRoundState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CS2TeamCurrentRoundState() {
    teamUrn_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bragi.Cs2Proto.internal_static_bragi_CS2TeamCurrentRoundState_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 2:
        return internalGetPlayerRoundStates();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bragi.Cs2Proto.internal_static_bragi_CS2TeamCurrentRoundState_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bragi.CS2TeamCurrentRoundState.class, com.bragi.CS2TeamCurrentRoundState.Builder.class);
  }

  public static final int TEAM_URN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object teamUrn_ = "";
  /**
   * <code>string team_urn = 1 [json_name = "teamUrn"];</code>
   * @return The teamUrn.
   */
  @java.lang.Override
  public java.lang.String getTeamUrn() {
    java.lang.Object ref = teamUrn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      teamUrn_ = s;
      return s;
    }
  }
  /**
   * <code>string team_urn = 1 [json_name = "teamUrn"];</code>
   * @return The bytes for teamUrn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTeamUrnBytes() {
    java.lang.Object ref = teamUrn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      teamUrn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYER_ROUND_STATES_FIELD_NUMBER = 2;
  private static final class PlayerRoundStatesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.bragi.CS2PlayerCurrentRoundState> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.bragi.CS2PlayerCurrentRoundState>newDefaultInstance(
                com.bragi.Cs2Proto.internal_static_bragi_CS2TeamCurrentRoundState_PlayerRoundStatesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.bragi.CS2PlayerCurrentRoundState.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.bragi.CS2PlayerCurrentRoundState> playerRoundStates_;
  private com.google.protobuf.MapField<java.lang.String, com.bragi.CS2PlayerCurrentRoundState>
  internalGetPlayerRoundStates() {
    if (playerRoundStates_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PlayerRoundStatesDefaultEntryHolder.defaultEntry);
    }
    return playerRoundStates_;
  }
  public int getPlayerRoundStatesCount() {
    return internalGetPlayerRoundStates().getMap().size();
  }
  /**
   * <pre>
   * keys are type of player_urn
   * </pre>
   *
   * <code>map&lt;string, .bragi.CS2PlayerCurrentRoundState&gt; player_round_states = 2 [json_name = "playerRoundStates"];</code>
   */
  @java.lang.Override
  public boolean containsPlayerRoundStates(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetPlayerRoundStates().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPlayerRoundStatesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.bragi.CS2PlayerCurrentRoundState> getPlayerRoundStates() {
    return getPlayerRoundStatesMap();
  }
  /**
   * <pre>
   * keys are type of player_urn
   * </pre>
   *
   * <code>map&lt;string, .bragi.CS2PlayerCurrentRoundState&gt; player_round_states = 2 [json_name = "playerRoundStates"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.bragi.CS2PlayerCurrentRoundState> getPlayerRoundStatesMap() {
    return internalGetPlayerRoundStates().getMap();
  }
  /**
   * <pre>
   * keys are type of player_urn
   * </pre>
   *
   * <code>map&lt;string, .bragi.CS2PlayerCurrentRoundState&gt; player_round_states = 2 [json_name = "playerRoundStates"];</code>
   */
  @java.lang.Override
  public /* nullable */
com.bragi.CS2PlayerCurrentRoundState getPlayerRoundStatesOrDefault(
      java.lang.String key,
      /* nullable */
com.bragi.CS2PlayerCurrentRoundState defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.bragi.CS2PlayerCurrentRoundState> map =
        internalGetPlayerRoundStates().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * keys are type of player_urn
   * </pre>
   *
   * <code>map&lt;string, .bragi.CS2PlayerCurrentRoundState&gt; player_round_states = 2 [json_name = "playerRoundStates"];</code>
   */
  @java.lang.Override
  public com.bragi.CS2PlayerCurrentRoundState getPlayerRoundStatesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.bragi.CS2PlayerCurrentRoundState> map =
        internalGetPlayerRoundStates().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(teamUrn_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, teamUrn_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetPlayerRoundStates(),
        PlayerRoundStatesDefaultEntryHolder.defaultEntry,
        2);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(teamUrn_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, teamUrn_);
    }
    for (java.util.Map.Entry<java.lang.String, com.bragi.CS2PlayerCurrentRoundState> entry
         : internalGetPlayerRoundStates().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.bragi.CS2PlayerCurrentRoundState>
      playerRoundStates__ = PlayerRoundStatesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, playerRoundStates__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bragi.CS2TeamCurrentRoundState)) {
      return super.equals(obj);
    }
    com.bragi.CS2TeamCurrentRoundState other = (com.bragi.CS2TeamCurrentRoundState) obj;

    if (!getTeamUrn()
        .equals(other.getTeamUrn())) return false;
    if (!internalGetPlayerRoundStates().equals(
        other.internalGetPlayerRoundStates())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEAM_URN_FIELD_NUMBER;
    hash = (53 * hash) + getTeamUrn().hashCode();
    if (!internalGetPlayerRoundStates().getMap().isEmpty()) {
      hash = (37 * hash) + PLAYER_ROUND_STATES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPlayerRoundStates().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bragi.CS2TeamCurrentRoundState parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.CS2TeamCurrentRoundState parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.CS2TeamCurrentRoundState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.CS2TeamCurrentRoundState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.CS2TeamCurrentRoundState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.CS2TeamCurrentRoundState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.CS2TeamCurrentRoundState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bragi.CS2TeamCurrentRoundState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bragi.CS2TeamCurrentRoundState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bragi.CS2TeamCurrentRoundState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bragi.CS2TeamCurrentRoundState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bragi.CS2TeamCurrentRoundState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bragi.CS2TeamCurrentRoundState prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bragi.CS2TeamCurrentRoundState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bragi.CS2TeamCurrentRoundState)
      com.bragi.CS2TeamCurrentRoundStateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bragi.Cs2Proto.internal_static_bragi_CS2TeamCurrentRoundState_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetPlayerRoundStates();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutablePlayerRoundStates();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bragi.Cs2Proto.internal_static_bragi_CS2TeamCurrentRoundState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bragi.CS2TeamCurrentRoundState.class, com.bragi.CS2TeamCurrentRoundState.Builder.class);
    }

    // Construct using com.bragi.CS2TeamCurrentRoundState.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      teamUrn_ = "";
      internalGetMutablePlayerRoundStates().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bragi.Cs2Proto.internal_static_bragi_CS2TeamCurrentRoundState_descriptor;
    }

    @java.lang.Override
    public com.bragi.CS2TeamCurrentRoundState getDefaultInstanceForType() {
      return com.bragi.CS2TeamCurrentRoundState.getDefaultInstance();
    }

    @java.lang.Override
    public com.bragi.CS2TeamCurrentRoundState build() {
      com.bragi.CS2TeamCurrentRoundState result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bragi.CS2TeamCurrentRoundState buildPartial() {
      com.bragi.CS2TeamCurrentRoundState result = new com.bragi.CS2TeamCurrentRoundState(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bragi.CS2TeamCurrentRoundState result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.teamUrn_ = teamUrn_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.playerRoundStates_ = internalGetPlayerRoundStates().build(PlayerRoundStatesDefaultEntryHolder.defaultEntry);
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bragi.CS2TeamCurrentRoundState) {
        return mergeFrom((com.bragi.CS2TeamCurrentRoundState)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bragi.CS2TeamCurrentRoundState other) {
      if (other == com.bragi.CS2TeamCurrentRoundState.getDefaultInstance()) return this;
      if (!other.getTeamUrn().isEmpty()) {
        teamUrn_ = other.teamUrn_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      internalGetMutablePlayerRoundStates().mergeFrom(
          other.internalGetPlayerRoundStates());
      bitField0_ |= 0x00000002;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              teamUrn_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.protobuf.MapEntry<java.lang.String, com.bragi.CS2PlayerCurrentRoundState>
              playerRoundStates__ = input.readMessage(
                  PlayerRoundStatesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutablePlayerRoundStates().ensureBuilderMap().put(
                  playerRoundStates__.getKey(), playerRoundStates__.getValue());
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object teamUrn_ = "";
    /**
     * <code>string team_urn = 1 [json_name = "teamUrn"];</code>
     * @return The teamUrn.
     */
    public java.lang.String getTeamUrn() {
      java.lang.Object ref = teamUrn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        teamUrn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string team_urn = 1 [json_name = "teamUrn"];</code>
     * @return The bytes for teamUrn.
     */
    public com.google.protobuf.ByteString
        getTeamUrnBytes() {
      java.lang.Object ref = teamUrn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teamUrn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string team_urn = 1 [json_name = "teamUrn"];</code>
     * @param value The teamUrn to set.
     * @return This builder for chaining.
     */
    public Builder setTeamUrn(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      teamUrn_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string team_urn = 1 [json_name = "teamUrn"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTeamUrn() {
      teamUrn_ = getDefaultInstance().getTeamUrn();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string team_urn = 1 [json_name = "teamUrn"];</code>
     * @param value The bytes for teamUrn to set.
     * @return This builder for chaining.
     */
    public Builder setTeamUrnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      teamUrn_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private static final class PlayerRoundStatesConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.bragi.CS2PlayerCurrentRoundStateOrBuilder, com.bragi.CS2PlayerCurrentRoundState> {
      @java.lang.Override
      public com.bragi.CS2PlayerCurrentRoundState build(com.bragi.CS2PlayerCurrentRoundStateOrBuilder val) {
        if (val instanceof com.bragi.CS2PlayerCurrentRoundState) { return (com.bragi.CS2PlayerCurrentRoundState) val; }
        return ((com.bragi.CS2PlayerCurrentRoundState.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.bragi.CS2PlayerCurrentRoundState> defaultEntry() {
        return PlayerRoundStatesDefaultEntryHolder.defaultEntry;
      }
    };
    private static final PlayerRoundStatesConverter playerRoundStatesConverter = new PlayerRoundStatesConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.bragi.CS2PlayerCurrentRoundStateOrBuilder, com.bragi.CS2PlayerCurrentRoundState, com.bragi.CS2PlayerCurrentRoundState.Builder> playerRoundStates_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.bragi.CS2PlayerCurrentRoundStateOrBuilder, com.bragi.CS2PlayerCurrentRoundState, com.bragi.CS2PlayerCurrentRoundState.Builder>
        internalGetPlayerRoundStates() {
      if (playerRoundStates_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(playerRoundStatesConverter);
      }
      return playerRoundStates_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.bragi.CS2PlayerCurrentRoundStateOrBuilder, com.bragi.CS2PlayerCurrentRoundState, com.bragi.CS2PlayerCurrentRoundState.Builder>
        internalGetMutablePlayerRoundStates() {
      if (playerRoundStates_ == null) {
        playerRoundStates_ = new com.google.protobuf.MapFieldBuilder<>(playerRoundStatesConverter);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return playerRoundStates_;
    }
    public int getPlayerRoundStatesCount() {
      return internalGetPlayerRoundStates().ensureBuilderMap().size();
    }
    /**
     * <pre>
     * keys are type of player_urn
     * </pre>
     *
     * <code>map&lt;string, .bragi.CS2PlayerCurrentRoundState&gt; player_round_states = 2 [json_name = "playerRoundStates"];</code>
     */
    @java.lang.Override
    public boolean containsPlayerRoundStates(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetPlayerRoundStates().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getPlayerRoundStatesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.bragi.CS2PlayerCurrentRoundState> getPlayerRoundStates() {
      return getPlayerRoundStatesMap();
    }
    /**
     * <pre>
     * keys are type of player_urn
     * </pre>
     *
     * <code>map&lt;string, .bragi.CS2PlayerCurrentRoundState&gt; player_round_states = 2 [json_name = "playerRoundStates"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.bragi.CS2PlayerCurrentRoundState> getPlayerRoundStatesMap() {
      return internalGetPlayerRoundStates().getImmutableMap();
    }
    /**
     * <pre>
     * keys are type of player_urn
     * </pre>
     *
     * <code>map&lt;string, .bragi.CS2PlayerCurrentRoundState&gt; player_round_states = 2 [json_name = "playerRoundStates"];</code>
     */
    @java.lang.Override
    public /* nullable */
com.bragi.CS2PlayerCurrentRoundState getPlayerRoundStatesOrDefault(
        java.lang.String key,
        /* nullable */
com.bragi.CS2PlayerCurrentRoundState defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.bragi.CS2PlayerCurrentRoundStateOrBuilder> map = internalGetMutablePlayerRoundStates().ensureBuilderMap();
      return map.containsKey(key) ? playerRoundStatesConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <pre>
     * keys are type of player_urn
     * </pre>
     *
     * <code>map&lt;string, .bragi.CS2PlayerCurrentRoundState&gt; player_round_states = 2 [json_name = "playerRoundStates"];</code>
     */
    @java.lang.Override
    public com.bragi.CS2PlayerCurrentRoundState getPlayerRoundStatesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.bragi.CS2PlayerCurrentRoundStateOrBuilder> map = internalGetMutablePlayerRoundStates().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return playerRoundStatesConverter.build(map.get(key));
    }
    public Builder clearPlayerRoundStates() {
      bitField0_ = (bitField0_ & ~0x00000002);
      internalGetMutablePlayerRoundStates().clear();
      return this;
    }
    /**
     * <pre>
     * keys are type of player_urn
     * </pre>
     *
     * <code>map&lt;string, .bragi.CS2PlayerCurrentRoundState&gt; player_round_states = 2 [json_name = "playerRoundStates"];</code>
     */
    public Builder removePlayerRoundStates(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutablePlayerRoundStates().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.bragi.CS2PlayerCurrentRoundState>
        getMutablePlayerRoundStates() {
      bitField0_ |= 0x00000002;
      return internalGetMutablePlayerRoundStates().ensureMessageMap();
    }
    /**
     * <pre>
     * keys are type of player_urn
     * </pre>
     *
     * <code>map&lt;string, .bragi.CS2PlayerCurrentRoundState&gt; player_round_states = 2 [json_name = "playerRoundStates"];</code>
     */
    public Builder putPlayerRoundStates(
        java.lang.String key,
        com.bragi.CS2PlayerCurrentRoundState value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutablePlayerRoundStates().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * keys are type of player_urn
     * </pre>
     *
     * <code>map&lt;string, .bragi.CS2PlayerCurrentRoundState&gt; player_round_states = 2 [json_name = "playerRoundStates"];</code>
     */
    public Builder putAllPlayerRoundStates(
        java.util.Map<java.lang.String, com.bragi.CS2PlayerCurrentRoundState> values) {
      for (java.util.Map.Entry<java.lang.String, com.bragi.CS2PlayerCurrentRoundState> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutablePlayerRoundStates().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * keys are type of player_urn
     * </pre>
     *
     * <code>map&lt;string, .bragi.CS2PlayerCurrentRoundState&gt; player_round_states = 2 [json_name = "playerRoundStates"];</code>
     */
    public com.bragi.CS2PlayerCurrentRoundState.Builder putPlayerRoundStatesBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.bragi.CS2PlayerCurrentRoundStateOrBuilder> builderMap = internalGetMutablePlayerRoundStates().ensureBuilderMap();
      com.bragi.CS2PlayerCurrentRoundStateOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.bragi.CS2PlayerCurrentRoundState.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.bragi.CS2PlayerCurrentRoundState) {
        entry = ((com.bragi.CS2PlayerCurrentRoundState) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.bragi.CS2PlayerCurrentRoundState.Builder) entry;
    }

    // @@protoc_insertion_point(builder_scope:bragi.CS2TeamCurrentRoundState)
  }

  // @@protoc_insertion_point(class_scope:bragi.CS2TeamCurrentRoundState)
  private static final com.bragi.CS2TeamCurrentRoundState DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bragi.CS2TeamCurrentRoundState();
  }

  public static com.bragi.CS2TeamCurrentRoundState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CS2TeamCurrentRoundState>
      PARSER = new com.google.protobuf.AbstractParser<CS2TeamCurrentRoundState>() {
    @java.lang.Override
    public CS2TeamCurrentRoundState parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CS2TeamCurrentRoundState> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CS2TeamCurrentRoundState> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bragi.CS2TeamCurrentRoundState getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

