// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/dota2.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

public interface Dota2AbilityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bragi.Dota2Ability)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 cooldown = 2 [json_name = "cooldown"];</code>
   * @return Whether the cooldown field is set.
   */
  boolean hasCooldown();
  /**
   * <code>optional int32 cooldown = 2 [json_name = "cooldown"];</code>
   * @return The cooldown.
   */
  int getCooldown();

  /**
   * <code>bool ultimate = 3 [json_name = "ultimate"];</code>
   * @return The ultimate.
   */
  boolean getUltimate();

  /**
   * <code>bool passive = 4 [json_name = "passive"];</code>
   * @return The passive.
   */
  boolean getPassive();

  /**
   * <code>bool can_cast = 5 [json_name = "canCast"];</code>
   * @return The canCast.
   */
  boolean getCanCast();
}
