// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/dota2.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

/**
 * Protobuf type {@code bragi.Dota2Ability}
 */
public final class Dota2Ability extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bragi.Dota2Ability)
    Dota2AbilityOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Dota2Ability.class.getName());
  }
  // Use Dota2Ability.newBuilder() to construct.
  private Dota2Ability(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Dota2Ability() {
    name_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bragi.Dota2Proto.internal_static_bragi_Dota2Ability_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bragi.Dota2Proto.internal_static_bragi_Dota2Ability_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bragi.Dota2Ability.class, com.bragi.Dota2Ability.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COOLDOWN_FIELD_NUMBER = 2;
  private int cooldown_ = 0;
  /**
   * <code>optional int32 cooldown = 2 [json_name = "cooldown"];</code>
   * @return Whether the cooldown field is set.
   */
  @java.lang.Override
  public boolean hasCooldown() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 cooldown = 2 [json_name = "cooldown"];</code>
   * @return The cooldown.
   */
  @java.lang.Override
  public int getCooldown() {
    return cooldown_;
  }

  public static final int ULTIMATE_FIELD_NUMBER = 3;
  private boolean ultimate_ = false;
  /**
   * <code>bool ultimate = 3 [json_name = "ultimate"];</code>
   * @return The ultimate.
   */
  @java.lang.Override
  public boolean getUltimate() {
    return ultimate_;
  }

  public static final int PASSIVE_FIELD_NUMBER = 4;
  private boolean passive_ = false;
  /**
   * <code>bool passive = 4 [json_name = "passive"];</code>
   * @return The passive.
   */
  @java.lang.Override
  public boolean getPassive() {
    return passive_;
  }

  public static final int CAN_CAST_FIELD_NUMBER = 5;
  private boolean canCast_ = false;
  /**
   * <code>bool can_cast = 5 [json_name = "canCast"];</code>
   * @return The canCast.
   */
  @java.lang.Override
  public boolean getCanCast() {
    return canCast_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(2, cooldown_);
    }
    if (ultimate_ != false) {
      output.writeBool(3, ultimate_);
    }
    if (passive_ != false) {
      output.writeBool(4, passive_);
    }
    if (canCast_ != false) {
      output.writeBool(5, canCast_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, cooldown_);
    }
    if (ultimate_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, ultimate_);
    }
    if (passive_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, passive_);
    }
    if (canCast_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, canCast_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bragi.Dota2Ability)) {
      return super.equals(obj);
    }
    com.bragi.Dota2Ability other = (com.bragi.Dota2Ability) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (hasCooldown() != other.hasCooldown()) return false;
    if (hasCooldown()) {
      if (getCooldown()
          != other.getCooldown()) return false;
    }
    if (getUltimate()
        != other.getUltimate()) return false;
    if (getPassive()
        != other.getPassive()) return false;
    if (getCanCast()
        != other.getCanCast()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasCooldown()) {
      hash = (37 * hash) + COOLDOWN_FIELD_NUMBER;
      hash = (53 * hash) + getCooldown();
    }
    hash = (37 * hash) + ULTIMATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getUltimate());
    hash = (37 * hash) + PASSIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPassive());
    hash = (37 * hash) + CAN_CAST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCanCast());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bragi.Dota2Ability parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.Dota2Ability parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.Dota2Ability parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.Dota2Ability parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.Dota2Ability parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.Dota2Ability parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.Dota2Ability parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bragi.Dota2Ability parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bragi.Dota2Ability parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bragi.Dota2Ability parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bragi.Dota2Ability parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bragi.Dota2Ability parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bragi.Dota2Ability prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bragi.Dota2Ability}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bragi.Dota2Ability)
      com.bragi.Dota2AbilityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bragi.Dota2Proto.internal_static_bragi_Dota2Ability_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bragi.Dota2Proto.internal_static_bragi_Dota2Ability_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bragi.Dota2Ability.class, com.bragi.Dota2Ability.Builder.class);
    }

    // Construct using com.bragi.Dota2Ability.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      cooldown_ = 0;
      ultimate_ = false;
      passive_ = false;
      canCast_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bragi.Dota2Proto.internal_static_bragi_Dota2Ability_descriptor;
    }

    @java.lang.Override
    public com.bragi.Dota2Ability getDefaultInstanceForType() {
      return com.bragi.Dota2Ability.getDefaultInstance();
    }

    @java.lang.Override
    public com.bragi.Dota2Ability build() {
      com.bragi.Dota2Ability result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bragi.Dota2Ability buildPartial() {
      com.bragi.Dota2Ability result = new com.bragi.Dota2Ability(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bragi.Dota2Ability result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.cooldown_ = cooldown_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.ultimate_ = ultimate_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.passive_ = passive_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.canCast_ = canCast_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bragi.Dota2Ability) {
        return mergeFrom((com.bragi.Dota2Ability)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bragi.Dota2Ability other) {
      if (other == com.bragi.Dota2Ability.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasCooldown()) {
        setCooldown(other.getCooldown());
      }
      if (other.getUltimate() != false) {
        setUltimate(other.getUltimate());
      }
      if (other.getPassive() != false) {
        setPassive(other.getPassive());
      }
      if (other.getCanCast() != false) {
        setCanCast(other.getCanCast());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              cooldown_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              ultimate_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              passive_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              canCast_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int cooldown_ ;
    /**
     * <code>optional int32 cooldown = 2 [json_name = "cooldown"];</code>
     * @return Whether the cooldown field is set.
     */
    @java.lang.Override
    public boolean hasCooldown() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 cooldown = 2 [json_name = "cooldown"];</code>
     * @return The cooldown.
     */
    @java.lang.Override
    public int getCooldown() {
      return cooldown_;
    }
    /**
     * <code>optional int32 cooldown = 2 [json_name = "cooldown"];</code>
     * @param value The cooldown to set.
     * @return This builder for chaining.
     */
    public Builder setCooldown(int value) {

      cooldown_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 cooldown = 2 [json_name = "cooldown"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCooldown() {
      bitField0_ = (bitField0_ & ~0x00000002);
      cooldown_ = 0;
      onChanged();
      return this;
    }

    private boolean ultimate_ ;
    /**
     * <code>bool ultimate = 3 [json_name = "ultimate"];</code>
     * @return The ultimate.
     */
    @java.lang.Override
    public boolean getUltimate() {
      return ultimate_;
    }
    /**
     * <code>bool ultimate = 3 [json_name = "ultimate"];</code>
     * @param value The ultimate to set.
     * @return This builder for chaining.
     */
    public Builder setUltimate(boolean value) {

      ultimate_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool ultimate = 3 [json_name = "ultimate"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUltimate() {
      bitField0_ = (bitField0_ & ~0x00000004);
      ultimate_ = false;
      onChanged();
      return this;
    }

    private boolean passive_ ;
    /**
     * <code>bool passive = 4 [json_name = "passive"];</code>
     * @return The passive.
     */
    @java.lang.Override
    public boolean getPassive() {
      return passive_;
    }
    /**
     * <code>bool passive = 4 [json_name = "passive"];</code>
     * @param value The passive to set.
     * @return This builder for chaining.
     */
    public Builder setPassive(boolean value) {

      passive_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool passive = 4 [json_name = "passive"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPassive() {
      bitField0_ = (bitField0_ & ~0x00000008);
      passive_ = false;
      onChanged();
      return this;
    }

    private boolean canCast_ ;
    /**
     * <code>bool can_cast = 5 [json_name = "canCast"];</code>
     * @return The canCast.
     */
    @java.lang.Override
    public boolean getCanCast() {
      return canCast_;
    }
    /**
     * <code>bool can_cast = 5 [json_name = "canCast"];</code>
     * @param value The canCast to set.
     * @return This builder for chaining.
     */
    public Builder setCanCast(boolean value) {

      canCast_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool can_cast = 5 [json_name = "canCast"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCanCast() {
      bitField0_ = (bitField0_ & ~0x00000010);
      canCast_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bragi.Dota2Ability)
  }

  // @@protoc_insertion_point(class_scope:bragi.Dota2Ability)
  private static final com.bragi.Dota2Ability DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bragi.Dota2Ability();
  }

  public static com.bragi.Dota2Ability getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Dota2Ability>
      PARSER = new com.google.protobuf.AbstractParser<Dota2Ability>() {
    @java.lang.Override
    public Dota2Ability parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Dota2Ability> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Dota2Ability> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bragi.Dota2Ability getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

