// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/dota2.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

public interface Dota2ItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bragi.Dota2Item)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 cooldown = 2 [json_name = "cooldown"];</code>
   * @return Whether the cooldown field is set.
   */
  boolean hasCooldown();
  /**
   * <code>optional int32 cooldown = 2 [json_name = "cooldown"];</code>
   * @return The cooldown.
   */
  int getCooldown();

  /**
   * <code>.bragi.Dota2ItemPosition position = 3 [json_name = "position"];</code>
   * @return The enum numeric value on the wire for position.
   */
  int getPositionValue();
  /**
   * <code>.bragi.Dota2ItemPosition position = 3 [json_name = "position"];</code>
   * @return The position.
   */
  com.bragi.Dota2ItemPosition getPosition();

  /**
   * <code>uint32 level = 4 [json_name = "level"];</code>
   * @return The level.
   */
  int getLevel();
}
