// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/dota2.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

/**
 * Protobuf type {@code bragi.Dota2PlayerPreviousMapState}
 */
public final class Dota2PlayerPreviousMapState extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bragi.Dota2PlayerPreviousMapState)
    Dota2PlayerPreviousMapStateOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Dota2PlayerPreviousMapState.class.getName());
  }
  // Use Dota2PlayerPreviousMapState.newBuilder() to construct.
  private Dota2PlayerPreviousMapState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Dota2PlayerPreviousMapState() {
    playerUrn_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bragi.Dota2Proto.internal_static_bragi_Dota2PlayerPreviousMapState_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bragi.Dota2Proto.internal_static_bragi_Dota2PlayerPreviousMapState_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bragi.Dota2PlayerPreviousMapState.class, com.bragi.Dota2PlayerPreviousMapState.Builder.class);
  }

  private int bitField0_;
  public static final int PLAYER_URN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object playerUrn_ = "";
  /**
   * <code>string player_urn = 1 [json_name = "playerUrn"];</code>
   * @return The playerUrn.
   */
  @java.lang.Override
  public java.lang.String getPlayerUrn() {
    java.lang.Object ref = playerUrn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      playerUrn_ = s;
      return s;
    }
  }
  /**
   * <code>string player_urn = 1 [json_name = "playerUrn"];</code>
   * @return The bytes for playerUrn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlayerUrnBytes() {
    java.lang.Object ref = playerUrn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      playerUrn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYER_INFO_FIELD_NUMBER = 2;
  private com.bragi.Dota2PlayerInfoState playerInfo_;
  /**
   * <code>.bragi.Dota2PlayerInfoState player_info = 2 [json_name = "playerInfo"];</code>
   * @return Whether the playerInfo field is set.
   */
  @java.lang.Override
  public boolean hasPlayerInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.bragi.Dota2PlayerInfoState player_info = 2 [json_name = "playerInfo"];</code>
   * @return The playerInfo.
   */
  @java.lang.Override
  public com.bragi.Dota2PlayerInfoState getPlayerInfo() {
    return playerInfo_ == null ? com.bragi.Dota2PlayerInfoState.getDefaultInstance() : playerInfo_;
  }
  /**
   * <code>.bragi.Dota2PlayerInfoState player_info = 2 [json_name = "playerInfo"];</code>
   */
  @java.lang.Override
  public com.bragi.Dota2PlayerInfoStateOrBuilder getPlayerInfoOrBuilder() {
    return playerInfo_ == null ? com.bragi.Dota2PlayerInfoState.getDefaultInstance() : playerInfo_;
  }

  public static final int STATISTICS_FIELD_NUMBER = 3;
  private com.bragi.Dota2PlayerStatisticsState statistics_;
  /**
   * <code>.bragi.Dota2PlayerStatisticsState statistics = 3 [json_name = "statistics"];</code>
   * @return Whether the statistics field is set.
   */
  @java.lang.Override
  public boolean hasStatistics() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.bragi.Dota2PlayerStatisticsState statistics = 3 [json_name = "statistics"];</code>
   * @return The statistics.
   */
  @java.lang.Override
  public com.bragi.Dota2PlayerStatisticsState getStatistics() {
    return statistics_ == null ? com.bragi.Dota2PlayerStatisticsState.getDefaultInstance() : statistics_;
  }
  /**
   * <code>.bragi.Dota2PlayerStatisticsState statistics = 3 [json_name = "statistics"];</code>
   */
  @java.lang.Override
  public com.bragi.Dota2PlayerStatisticsStateOrBuilder getStatisticsOrBuilder() {
    return statistics_ == null ? com.bragi.Dota2PlayerStatisticsState.getDefaultInstance() : statistics_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerUrn_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, playerUrn_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getPlayerInfo());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getStatistics());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerUrn_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, playerUrn_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPlayerInfo());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getStatistics());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bragi.Dota2PlayerPreviousMapState)) {
      return super.equals(obj);
    }
    com.bragi.Dota2PlayerPreviousMapState other = (com.bragi.Dota2PlayerPreviousMapState) obj;

    if (!getPlayerUrn()
        .equals(other.getPlayerUrn())) return false;
    if (hasPlayerInfo() != other.hasPlayerInfo()) return false;
    if (hasPlayerInfo()) {
      if (!getPlayerInfo()
          .equals(other.getPlayerInfo())) return false;
    }
    if (hasStatistics() != other.hasStatistics()) return false;
    if (hasStatistics()) {
      if (!getStatistics()
          .equals(other.getStatistics())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PLAYER_URN_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerUrn().hashCode();
    if (hasPlayerInfo()) {
      hash = (37 * hash) + PLAYER_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerInfo().hashCode();
    }
    if (hasStatistics()) {
      hash = (37 * hash) + STATISTICS_FIELD_NUMBER;
      hash = (53 * hash) + getStatistics().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bragi.Dota2PlayerPreviousMapState parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.Dota2PlayerPreviousMapState parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.Dota2PlayerPreviousMapState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.Dota2PlayerPreviousMapState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.Dota2PlayerPreviousMapState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.Dota2PlayerPreviousMapState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.Dota2PlayerPreviousMapState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bragi.Dota2PlayerPreviousMapState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bragi.Dota2PlayerPreviousMapState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bragi.Dota2PlayerPreviousMapState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bragi.Dota2PlayerPreviousMapState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bragi.Dota2PlayerPreviousMapState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bragi.Dota2PlayerPreviousMapState prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bragi.Dota2PlayerPreviousMapState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bragi.Dota2PlayerPreviousMapState)
      com.bragi.Dota2PlayerPreviousMapStateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bragi.Dota2Proto.internal_static_bragi_Dota2PlayerPreviousMapState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bragi.Dota2Proto.internal_static_bragi_Dota2PlayerPreviousMapState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bragi.Dota2PlayerPreviousMapState.class, com.bragi.Dota2PlayerPreviousMapState.Builder.class);
    }

    // Construct using com.bragi.Dota2PlayerPreviousMapState.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getPlayerInfoFieldBuilder();
        getStatisticsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      playerUrn_ = "";
      playerInfo_ = null;
      if (playerInfoBuilder_ != null) {
        playerInfoBuilder_.dispose();
        playerInfoBuilder_ = null;
      }
      statistics_ = null;
      if (statisticsBuilder_ != null) {
        statisticsBuilder_.dispose();
        statisticsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bragi.Dota2Proto.internal_static_bragi_Dota2PlayerPreviousMapState_descriptor;
    }

    @java.lang.Override
    public com.bragi.Dota2PlayerPreviousMapState getDefaultInstanceForType() {
      return com.bragi.Dota2PlayerPreviousMapState.getDefaultInstance();
    }

    @java.lang.Override
    public com.bragi.Dota2PlayerPreviousMapState build() {
      com.bragi.Dota2PlayerPreviousMapState result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bragi.Dota2PlayerPreviousMapState buildPartial() {
      com.bragi.Dota2PlayerPreviousMapState result = new com.bragi.Dota2PlayerPreviousMapState(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bragi.Dota2PlayerPreviousMapState result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.playerUrn_ = playerUrn_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.playerInfo_ = playerInfoBuilder_ == null
            ? playerInfo_
            : playerInfoBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.statistics_ = statisticsBuilder_ == null
            ? statistics_
            : statisticsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bragi.Dota2PlayerPreviousMapState) {
        return mergeFrom((com.bragi.Dota2PlayerPreviousMapState)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bragi.Dota2PlayerPreviousMapState other) {
      if (other == com.bragi.Dota2PlayerPreviousMapState.getDefaultInstance()) return this;
      if (!other.getPlayerUrn().isEmpty()) {
        playerUrn_ = other.playerUrn_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasPlayerInfo()) {
        mergePlayerInfo(other.getPlayerInfo());
      }
      if (other.hasStatistics()) {
        mergeStatistics(other.getStatistics());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              playerUrn_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPlayerInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getStatisticsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object playerUrn_ = "";
    /**
     * <code>string player_urn = 1 [json_name = "playerUrn"];</code>
     * @return The playerUrn.
     */
    public java.lang.String getPlayerUrn() {
      java.lang.Object ref = playerUrn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerUrn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string player_urn = 1 [json_name = "playerUrn"];</code>
     * @return The bytes for playerUrn.
     */
    public com.google.protobuf.ByteString
        getPlayerUrnBytes() {
      java.lang.Object ref = playerUrn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerUrn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string player_urn = 1 [json_name = "playerUrn"];</code>
     * @param value The playerUrn to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerUrn(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      playerUrn_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string player_urn = 1 [json_name = "playerUrn"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerUrn() {
      playerUrn_ = getDefaultInstance().getPlayerUrn();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string player_urn = 1 [json_name = "playerUrn"];</code>
     * @param value The bytes for playerUrn to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerUrnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      playerUrn_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.bragi.Dota2PlayerInfoState playerInfo_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.Dota2PlayerInfoState, com.bragi.Dota2PlayerInfoState.Builder, com.bragi.Dota2PlayerInfoStateOrBuilder> playerInfoBuilder_;
    /**
     * <code>.bragi.Dota2PlayerInfoState player_info = 2 [json_name = "playerInfo"];</code>
     * @return Whether the playerInfo field is set.
     */
    public boolean hasPlayerInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.bragi.Dota2PlayerInfoState player_info = 2 [json_name = "playerInfo"];</code>
     * @return The playerInfo.
     */
    public com.bragi.Dota2PlayerInfoState getPlayerInfo() {
      if (playerInfoBuilder_ == null) {
        return playerInfo_ == null ? com.bragi.Dota2PlayerInfoState.getDefaultInstance() : playerInfo_;
      } else {
        return playerInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.bragi.Dota2PlayerInfoState player_info = 2 [json_name = "playerInfo"];</code>
     */
    public Builder setPlayerInfo(com.bragi.Dota2PlayerInfoState value) {
      if (playerInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        playerInfo_ = value;
      } else {
        playerInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.Dota2PlayerInfoState player_info = 2 [json_name = "playerInfo"];</code>
     */
    public Builder setPlayerInfo(
        com.bragi.Dota2PlayerInfoState.Builder builderForValue) {
      if (playerInfoBuilder_ == null) {
        playerInfo_ = builderForValue.build();
      } else {
        playerInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.Dota2PlayerInfoState player_info = 2 [json_name = "playerInfo"];</code>
     */
    public Builder mergePlayerInfo(com.bragi.Dota2PlayerInfoState value) {
      if (playerInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          playerInfo_ != null &&
          playerInfo_ != com.bragi.Dota2PlayerInfoState.getDefaultInstance()) {
          getPlayerInfoBuilder().mergeFrom(value);
        } else {
          playerInfo_ = value;
        }
      } else {
        playerInfoBuilder_.mergeFrom(value);
      }
      if (playerInfo_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.bragi.Dota2PlayerInfoState player_info = 2 [json_name = "playerInfo"];</code>
     */
    public Builder clearPlayerInfo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      playerInfo_ = null;
      if (playerInfoBuilder_ != null) {
        playerInfoBuilder_.dispose();
        playerInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.Dota2PlayerInfoState player_info = 2 [json_name = "playerInfo"];</code>
     */
    public com.bragi.Dota2PlayerInfoState.Builder getPlayerInfoBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPlayerInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.bragi.Dota2PlayerInfoState player_info = 2 [json_name = "playerInfo"];</code>
     */
    public com.bragi.Dota2PlayerInfoStateOrBuilder getPlayerInfoOrBuilder() {
      if (playerInfoBuilder_ != null) {
        return playerInfoBuilder_.getMessageOrBuilder();
      } else {
        return playerInfo_ == null ?
            com.bragi.Dota2PlayerInfoState.getDefaultInstance() : playerInfo_;
      }
    }
    /**
     * <code>.bragi.Dota2PlayerInfoState player_info = 2 [json_name = "playerInfo"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.Dota2PlayerInfoState, com.bragi.Dota2PlayerInfoState.Builder, com.bragi.Dota2PlayerInfoStateOrBuilder> 
        getPlayerInfoFieldBuilder() {
      if (playerInfoBuilder_ == null) {
        playerInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bragi.Dota2PlayerInfoState, com.bragi.Dota2PlayerInfoState.Builder, com.bragi.Dota2PlayerInfoStateOrBuilder>(
                getPlayerInfo(),
                getParentForChildren(),
                isClean());
        playerInfo_ = null;
      }
      return playerInfoBuilder_;
    }

    private com.bragi.Dota2PlayerStatisticsState statistics_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.Dota2PlayerStatisticsState, com.bragi.Dota2PlayerStatisticsState.Builder, com.bragi.Dota2PlayerStatisticsStateOrBuilder> statisticsBuilder_;
    /**
     * <code>.bragi.Dota2PlayerStatisticsState statistics = 3 [json_name = "statistics"];</code>
     * @return Whether the statistics field is set.
     */
    public boolean hasStatistics() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.bragi.Dota2PlayerStatisticsState statistics = 3 [json_name = "statistics"];</code>
     * @return The statistics.
     */
    public com.bragi.Dota2PlayerStatisticsState getStatistics() {
      if (statisticsBuilder_ == null) {
        return statistics_ == null ? com.bragi.Dota2PlayerStatisticsState.getDefaultInstance() : statistics_;
      } else {
        return statisticsBuilder_.getMessage();
      }
    }
    /**
     * <code>.bragi.Dota2PlayerStatisticsState statistics = 3 [json_name = "statistics"];</code>
     */
    public Builder setStatistics(com.bragi.Dota2PlayerStatisticsState value) {
      if (statisticsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        statistics_ = value;
      } else {
        statisticsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.Dota2PlayerStatisticsState statistics = 3 [json_name = "statistics"];</code>
     */
    public Builder setStatistics(
        com.bragi.Dota2PlayerStatisticsState.Builder builderForValue) {
      if (statisticsBuilder_ == null) {
        statistics_ = builderForValue.build();
      } else {
        statisticsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.Dota2PlayerStatisticsState statistics = 3 [json_name = "statistics"];</code>
     */
    public Builder mergeStatistics(com.bragi.Dota2PlayerStatisticsState value) {
      if (statisticsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          statistics_ != null &&
          statistics_ != com.bragi.Dota2PlayerStatisticsState.getDefaultInstance()) {
          getStatisticsBuilder().mergeFrom(value);
        } else {
          statistics_ = value;
        }
      } else {
        statisticsBuilder_.mergeFrom(value);
      }
      if (statistics_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.bragi.Dota2PlayerStatisticsState statistics = 3 [json_name = "statistics"];</code>
     */
    public Builder clearStatistics() {
      bitField0_ = (bitField0_ & ~0x00000004);
      statistics_ = null;
      if (statisticsBuilder_ != null) {
        statisticsBuilder_.dispose();
        statisticsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.Dota2PlayerStatisticsState statistics = 3 [json_name = "statistics"];</code>
     */
    public com.bragi.Dota2PlayerStatisticsState.Builder getStatisticsBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getStatisticsFieldBuilder().getBuilder();
    }
    /**
     * <code>.bragi.Dota2PlayerStatisticsState statistics = 3 [json_name = "statistics"];</code>
     */
    public com.bragi.Dota2PlayerStatisticsStateOrBuilder getStatisticsOrBuilder() {
      if (statisticsBuilder_ != null) {
        return statisticsBuilder_.getMessageOrBuilder();
      } else {
        return statistics_ == null ?
            com.bragi.Dota2PlayerStatisticsState.getDefaultInstance() : statistics_;
      }
    }
    /**
     * <code>.bragi.Dota2PlayerStatisticsState statistics = 3 [json_name = "statistics"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.Dota2PlayerStatisticsState, com.bragi.Dota2PlayerStatisticsState.Builder, com.bragi.Dota2PlayerStatisticsStateOrBuilder> 
        getStatisticsFieldBuilder() {
      if (statisticsBuilder_ == null) {
        statisticsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bragi.Dota2PlayerStatisticsState, com.bragi.Dota2PlayerStatisticsState.Builder, com.bragi.Dota2PlayerStatisticsStateOrBuilder>(
                getStatistics(),
                getParentForChildren(),
                isClean());
        statistics_ = null;
      }
      return statisticsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:bragi.Dota2PlayerPreviousMapState)
  }

  // @@protoc_insertion_point(class_scope:bragi.Dota2PlayerPreviousMapState)
  private static final com.bragi.Dota2PlayerPreviousMapState DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bragi.Dota2PlayerPreviousMapState();
  }

  public static com.bragi.Dota2PlayerPreviousMapState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Dota2PlayerPreviousMapState>
      PARSER = new com.google.protobuf.AbstractParser<Dota2PlayerPreviousMapState>() {
    @java.lang.Override
    public Dota2PlayerPreviousMapState parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Dota2PlayerPreviousMapState> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Dota2PlayerPreviousMapState> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bragi.Dota2PlayerPreviousMapState getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

