// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/lol.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

/**
 * Protobuf type {@code bragi.LolCurrentMapState}
 */
public final class LolCurrentMapState extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bragi.LolCurrentMapState)
    LolCurrentMapStateOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      LolCurrentMapState.class.getName());
  }
  // Use LolCurrentMapState.newBuilder() to construct.
  private LolCurrentMapState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LolCurrentMapState() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bragi.LolProto.internal_static_bragi_LolCurrentMapState_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 4:
        return internalGetTeams();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bragi.LolProto.internal_static_bragi_LolCurrentMapState_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bragi.LolCurrentMapState.class, com.bragi.LolCurrentMapState.Builder.class);
  }

  private int bitField0_;
  public static final int MAP_ORDER_FIELD_NUMBER = 1;
  private int mapOrder_ = 0;
  /**
   * <code>uint32 map_order = 1 [json_name = "mapOrder"];</code>
   * @return The mapOrder.
   */
  @java.lang.Override
  public int getMapOrder() {
    return mapOrder_;
  }

  public static final int MAP_PAUSED_FIELD_NUMBER = 2;
  private boolean mapPaused_ = false;
  /**
   * <code>bool map_paused = 2 [json_name = "mapPaused"];</code>
   * @return The mapPaused.
   */
  @java.lang.Override
  public boolean getMapPaused() {
    return mapPaused_;
  }

  public static final int GAME_TIME_FIELD_NUMBER = 3;
  private com.bragi.LolCurrentMapTimeState gameTime_;
  /**
   * <code>.bragi.LolCurrentMapTimeState game_time = 3 [json_name = "gameTime"];</code>
   * @return Whether the gameTime field is set.
   */
  @java.lang.Override
  public boolean hasGameTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.bragi.LolCurrentMapTimeState game_time = 3 [json_name = "gameTime"];</code>
   * @return The gameTime.
   */
  @java.lang.Override
  public com.bragi.LolCurrentMapTimeState getGameTime() {
    return gameTime_ == null ? com.bragi.LolCurrentMapTimeState.getDefaultInstance() : gameTime_;
  }
  /**
   * <code>.bragi.LolCurrentMapTimeState game_time = 3 [json_name = "gameTime"];</code>
   */
  @java.lang.Override
  public com.bragi.LolCurrentMapTimeStateOrBuilder getGameTimeOrBuilder() {
    return gameTime_ == null ? com.bragi.LolCurrentMapTimeState.getDefaultInstance() : gameTime_;
  }

  public static final int TEAMS_FIELD_NUMBER = 4;
  private static final class TeamsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.bragi.LolTeamCurrentMapState> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.bragi.LolTeamCurrentMapState>newDefaultInstance(
                com.bragi.LolProto.internal_static_bragi_LolCurrentMapState_TeamsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.bragi.LolTeamCurrentMapState.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.bragi.LolTeamCurrentMapState> teams_;
  private com.google.protobuf.MapField<java.lang.String, com.bragi.LolTeamCurrentMapState>
  internalGetTeams() {
    if (teams_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TeamsDefaultEntryHolder.defaultEntry);
    }
    return teams_;
  }
  public int getTeamsCount() {
    return internalGetTeams().getMap().size();
  }
  /**
   * <code>map&lt;string, .bragi.LolTeamCurrentMapState&gt; teams = 4 [json_name = "teams"];</code>
   */
  @java.lang.Override
  public boolean containsTeams(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetTeams().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTeamsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.bragi.LolTeamCurrentMapState> getTeams() {
    return getTeamsMap();
  }
  /**
   * <code>map&lt;string, .bragi.LolTeamCurrentMapState&gt; teams = 4 [json_name = "teams"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.bragi.LolTeamCurrentMapState> getTeamsMap() {
    return internalGetTeams().getMap();
  }
  /**
   * <code>map&lt;string, .bragi.LolTeamCurrentMapState&gt; teams = 4 [json_name = "teams"];</code>
   */
  @java.lang.Override
  public /* nullable */
com.bragi.LolTeamCurrentMapState getTeamsOrDefault(
      java.lang.String key,
      /* nullable */
com.bragi.LolTeamCurrentMapState defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.bragi.LolTeamCurrentMapState> map =
        internalGetTeams().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .bragi.LolTeamCurrentMapState&gt; teams = 4 [json_name = "teams"];</code>
   */
  @java.lang.Override
  public com.bragi.LolTeamCurrentMapState getTeamsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.bragi.LolTeamCurrentMapState> map =
        internalGetTeams().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TURRETS_FIELD_NUMBER = 5;
  private com.bragi.LolTurrets turrets_;
  /**
   * <code>.bragi.LolTurrets turrets = 5 [json_name = "turrets"];</code>
   * @return Whether the turrets field is set.
   */
  @java.lang.Override
  public boolean hasTurrets() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.bragi.LolTurrets turrets = 5 [json_name = "turrets"];</code>
   * @return The turrets.
   */
  @java.lang.Override
  public com.bragi.LolTurrets getTurrets() {
    return turrets_ == null ? com.bragi.LolTurrets.getDefaultInstance() : turrets_;
  }
  /**
   * <code>.bragi.LolTurrets turrets = 5 [json_name = "turrets"];</code>
   */
  @java.lang.Override
  public com.bragi.LolTurretsOrBuilder getTurretsOrBuilder() {
    return turrets_ == null ? com.bragi.LolTurrets.getDefaultInstance() : turrets_;
  }

  public static final int INHIBITORS_FIELD_NUMBER = 6;
  private com.bragi.LolInhibitors inhibitors_;
  /**
   * <code>.bragi.LolInhibitors inhibitors = 6 [json_name = "inhibitors"];</code>
   * @return Whether the inhibitors field is set.
   */
  @java.lang.Override
  public boolean hasInhibitors() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.bragi.LolInhibitors inhibitors = 6 [json_name = "inhibitors"];</code>
   * @return The inhibitors.
   */
  @java.lang.Override
  public com.bragi.LolInhibitors getInhibitors() {
    return inhibitors_ == null ? com.bragi.LolInhibitors.getDefaultInstance() : inhibitors_;
  }
  /**
   * <code>.bragi.LolInhibitors inhibitors = 6 [json_name = "inhibitors"];</code>
   */
  @java.lang.Override
  public com.bragi.LolInhibitorsOrBuilder getInhibitorsOrBuilder() {
    return inhibitors_ == null ? com.bragi.LolInhibitors.getDefaultInstance() : inhibitors_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (mapOrder_ != 0) {
      output.writeUInt32(1, mapOrder_);
    }
    if (mapPaused_ != false) {
      output.writeBool(2, mapPaused_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getGameTime());
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetTeams(),
        TeamsDefaultEntryHolder.defaultEntry,
        4);
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getTurrets());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(6, getInhibitors());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mapOrder_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, mapOrder_);
    }
    if (mapPaused_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, mapPaused_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getGameTime());
    }
    for (java.util.Map.Entry<java.lang.String, com.bragi.LolTeamCurrentMapState> entry
         : internalGetTeams().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.bragi.LolTeamCurrentMapState>
      teams__ = TeamsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, teams__);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getTurrets());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getInhibitors());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bragi.LolCurrentMapState)) {
      return super.equals(obj);
    }
    com.bragi.LolCurrentMapState other = (com.bragi.LolCurrentMapState) obj;

    if (getMapOrder()
        != other.getMapOrder()) return false;
    if (getMapPaused()
        != other.getMapPaused()) return false;
    if (hasGameTime() != other.hasGameTime()) return false;
    if (hasGameTime()) {
      if (!getGameTime()
          .equals(other.getGameTime())) return false;
    }
    if (!internalGetTeams().equals(
        other.internalGetTeams())) return false;
    if (hasTurrets() != other.hasTurrets()) return false;
    if (hasTurrets()) {
      if (!getTurrets()
          .equals(other.getTurrets())) return false;
    }
    if (hasInhibitors() != other.hasInhibitors()) return false;
    if (hasInhibitors()) {
      if (!getInhibitors()
          .equals(other.getInhibitors())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAP_ORDER_FIELD_NUMBER;
    hash = (53 * hash) + getMapOrder();
    hash = (37 * hash) + MAP_PAUSED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMapPaused());
    if (hasGameTime()) {
      hash = (37 * hash) + GAME_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getGameTime().hashCode();
    }
    if (!internalGetTeams().getMap().isEmpty()) {
      hash = (37 * hash) + TEAMS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTeams().hashCode();
    }
    if (hasTurrets()) {
      hash = (37 * hash) + TURRETS_FIELD_NUMBER;
      hash = (53 * hash) + getTurrets().hashCode();
    }
    if (hasInhibitors()) {
      hash = (37 * hash) + INHIBITORS_FIELD_NUMBER;
      hash = (53 * hash) + getInhibitors().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bragi.LolCurrentMapState parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.LolCurrentMapState parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.LolCurrentMapState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.LolCurrentMapState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.LolCurrentMapState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.LolCurrentMapState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.LolCurrentMapState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bragi.LolCurrentMapState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bragi.LolCurrentMapState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bragi.LolCurrentMapState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bragi.LolCurrentMapState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bragi.LolCurrentMapState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bragi.LolCurrentMapState prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bragi.LolCurrentMapState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bragi.LolCurrentMapState)
      com.bragi.LolCurrentMapStateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bragi.LolProto.internal_static_bragi_LolCurrentMapState_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetTeams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableTeams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bragi.LolProto.internal_static_bragi_LolCurrentMapState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bragi.LolCurrentMapState.class, com.bragi.LolCurrentMapState.Builder.class);
    }

    // Construct using com.bragi.LolCurrentMapState.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getGameTimeFieldBuilder();
        getTurretsFieldBuilder();
        getInhibitorsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      mapOrder_ = 0;
      mapPaused_ = false;
      gameTime_ = null;
      if (gameTimeBuilder_ != null) {
        gameTimeBuilder_.dispose();
        gameTimeBuilder_ = null;
      }
      internalGetMutableTeams().clear();
      turrets_ = null;
      if (turretsBuilder_ != null) {
        turretsBuilder_.dispose();
        turretsBuilder_ = null;
      }
      inhibitors_ = null;
      if (inhibitorsBuilder_ != null) {
        inhibitorsBuilder_.dispose();
        inhibitorsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bragi.LolProto.internal_static_bragi_LolCurrentMapState_descriptor;
    }

    @java.lang.Override
    public com.bragi.LolCurrentMapState getDefaultInstanceForType() {
      return com.bragi.LolCurrentMapState.getDefaultInstance();
    }

    @java.lang.Override
    public com.bragi.LolCurrentMapState build() {
      com.bragi.LolCurrentMapState result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bragi.LolCurrentMapState buildPartial() {
      com.bragi.LolCurrentMapState result = new com.bragi.LolCurrentMapState(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bragi.LolCurrentMapState result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.mapOrder_ = mapOrder_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.mapPaused_ = mapPaused_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.gameTime_ = gameTimeBuilder_ == null
            ? gameTime_
            : gameTimeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.teams_ = internalGetTeams().build(TeamsDefaultEntryHolder.defaultEntry);
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.turrets_ = turretsBuilder_ == null
            ? turrets_
            : turretsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.inhibitors_ = inhibitorsBuilder_ == null
            ? inhibitors_
            : inhibitorsBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bragi.LolCurrentMapState) {
        return mergeFrom((com.bragi.LolCurrentMapState)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bragi.LolCurrentMapState other) {
      if (other == com.bragi.LolCurrentMapState.getDefaultInstance()) return this;
      if (other.getMapOrder() != 0) {
        setMapOrder(other.getMapOrder());
      }
      if (other.getMapPaused() != false) {
        setMapPaused(other.getMapPaused());
      }
      if (other.hasGameTime()) {
        mergeGameTime(other.getGameTime());
      }
      internalGetMutableTeams().mergeFrom(
          other.internalGetTeams());
      bitField0_ |= 0x00000008;
      if (other.hasTurrets()) {
        mergeTurrets(other.getTurrets());
      }
      if (other.hasInhibitors()) {
        mergeInhibitors(other.getInhibitors());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              mapOrder_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              mapPaused_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getGameTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.google.protobuf.MapEntry<java.lang.String, com.bragi.LolTeamCurrentMapState>
              teams__ = input.readMessage(
                  TeamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableTeams().ensureBuilderMap().put(
                  teams__.getKey(), teams__.getValue());
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getTurretsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getInhibitorsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int mapOrder_ ;
    /**
     * <code>uint32 map_order = 1 [json_name = "mapOrder"];</code>
     * @return The mapOrder.
     */
    @java.lang.Override
    public int getMapOrder() {
      return mapOrder_;
    }
    /**
     * <code>uint32 map_order = 1 [json_name = "mapOrder"];</code>
     * @param value The mapOrder to set.
     * @return This builder for chaining.
     */
    public Builder setMapOrder(int value) {

      mapOrder_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 map_order = 1 [json_name = "mapOrder"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMapOrder() {
      bitField0_ = (bitField0_ & ~0x00000001);
      mapOrder_ = 0;
      onChanged();
      return this;
    }

    private boolean mapPaused_ ;
    /**
     * <code>bool map_paused = 2 [json_name = "mapPaused"];</code>
     * @return The mapPaused.
     */
    @java.lang.Override
    public boolean getMapPaused() {
      return mapPaused_;
    }
    /**
     * <code>bool map_paused = 2 [json_name = "mapPaused"];</code>
     * @param value The mapPaused to set.
     * @return This builder for chaining.
     */
    public Builder setMapPaused(boolean value) {

      mapPaused_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool map_paused = 2 [json_name = "mapPaused"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMapPaused() {
      bitField0_ = (bitField0_ & ~0x00000002);
      mapPaused_ = false;
      onChanged();
      return this;
    }

    private com.bragi.LolCurrentMapTimeState gameTime_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.LolCurrentMapTimeState, com.bragi.LolCurrentMapTimeState.Builder, com.bragi.LolCurrentMapTimeStateOrBuilder> gameTimeBuilder_;
    /**
     * <code>.bragi.LolCurrentMapTimeState game_time = 3 [json_name = "gameTime"];</code>
     * @return Whether the gameTime field is set.
     */
    public boolean hasGameTime() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.bragi.LolCurrentMapTimeState game_time = 3 [json_name = "gameTime"];</code>
     * @return The gameTime.
     */
    public com.bragi.LolCurrentMapTimeState getGameTime() {
      if (gameTimeBuilder_ == null) {
        return gameTime_ == null ? com.bragi.LolCurrentMapTimeState.getDefaultInstance() : gameTime_;
      } else {
        return gameTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.bragi.LolCurrentMapTimeState game_time = 3 [json_name = "gameTime"];</code>
     */
    public Builder setGameTime(com.bragi.LolCurrentMapTimeState value) {
      if (gameTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gameTime_ = value;
      } else {
        gameTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.LolCurrentMapTimeState game_time = 3 [json_name = "gameTime"];</code>
     */
    public Builder setGameTime(
        com.bragi.LolCurrentMapTimeState.Builder builderForValue) {
      if (gameTimeBuilder_ == null) {
        gameTime_ = builderForValue.build();
      } else {
        gameTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.LolCurrentMapTimeState game_time = 3 [json_name = "gameTime"];</code>
     */
    public Builder mergeGameTime(com.bragi.LolCurrentMapTimeState value) {
      if (gameTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          gameTime_ != null &&
          gameTime_ != com.bragi.LolCurrentMapTimeState.getDefaultInstance()) {
          getGameTimeBuilder().mergeFrom(value);
        } else {
          gameTime_ = value;
        }
      } else {
        gameTimeBuilder_.mergeFrom(value);
      }
      if (gameTime_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.bragi.LolCurrentMapTimeState game_time = 3 [json_name = "gameTime"];</code>
     */
    public Builder clearGameTime() {
      bitField0_ = (bitField0_ & ~0x00000004);
      gameTime_ = null;
      if (gameTimeBuilder_ != null) {
        gameTimeBuilder_.dispose();
        gameTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.LolCurrentMapTimeState game_time = 3 [json_name = "gameTime"];</code>
     */
    public com.bragi.LolCurrentMapTimeState.Builder getGameTimeBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getGameTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.bragi.LolCurrentMapTimeState game_time = 3 [json_name = "gameTime"];</code>
     */
    public com.bragi.LolCurrentMapTimeStateOrBuilder getGameTimeOrBuilder() {
      if (gameTimeBuilder_ != null) {
        return gameTimeBuilder_.getMessageOrBuilder();
      } else {
        return gameTime_ == null ?
            com.bragi.LolCurrentMapTimeState.getDefaultInstance() : gameTime_;
      }
    }
    /**
     * <code>.bragi.LolCurrentMapTimeState game_time = 3 [json_name = "gameTime"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.LolCurrentMapTimeState, com.bragi.LolCurrentMapTimeState.Builder, com.bragi.LolCurrentMapTimeStateOrBuilder> 
        getGameTimeFieldBuilder() {
      if (gameTimeBuilder_ == null) {
        gameTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bragi.LolCurrentMapTimeState, com.bragi.LolCurrentMapTimeState.Builder, com.bragi.LolCurrentMapTimeStateOrBuilder>(
                getGameTime(),
                getParentForChildren(),
                isClean());
        gameTime_ = null;
      }
      return gameTimeBuilder_;
    }

    private static final class TeamsConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.bragi.LolTeamCurrentMapStateOrBuilder, com.bragi.LolTeamCurrentMapState> {
      @java.lang.Override
      public com.bragi.LolTeamCurrentMapState build(com.bragi.LolTeamCurrentMapStateOrBuilder val) {
        if (val instanceof com.bragi.LolTeamCurrentMapState) { return (com.bragi.LolTeamCurrentMapState) val; }
        return ((com.bragi.LolTeamCurrentMapState.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.bragi.LolTeamCurrentMapState> defaultEntry() {
        return TeamsDefaultEntryHolder.defaultEntry;
      }
    };
    private static final TeamsConverter teamsConverter = new TeamsConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.bragi.LolTeamCurrentMapStateOrBuilder, com.bragi.LolTeamCurrentMapState, com.bragi.LolTeamCurrentMapState.Builder> teams_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.bragi.LolTeamCurrentMapStateOrBuilder, com.bragi.LolTeamCurrentMapState, com.bragi.LolTeamCurrentMapState.Builder>
        internalGetTeams() {
      if (teams_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(teamsConverter);
      }
      return teams_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.bragi.LolTeamCurrentMapStateOrBuilder, com.bragi.LolTeamCurrentMapState, com.bragi.LolTeamCurrentMapState.Builder>
        internalGetMutableTeams() {
      if (teams_ == null) {
        teams_ = new com.google.protobuf.MapFieldBuilder<>(teamsConverter);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return teams_;
    }
    public int getTeamsCount() {
      return internalGetTeams().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .bragi.LolTeamCurrentMapState&gt; teams = 4 [json_name = "teams"];</code>
     */
    @java.lang.Override
    public boolean containsTeams(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetTeams().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getTeamsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.bragi.LolTeamCurrentMapState> getTeams() {
      return getTeamsMap();
    }
    /**
     * <code>map&lt;string, .bragi.LolTeamCurrentMapState&gt; teams = 4 [json_name = "teams"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.bragi.LolTeamCurrentMapState> getTeamsMap() {
      return internalGetTeams().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .bragi.LolTeamCurrentMapState&gt; teams = 4 [json_name = "teams"];</code>
     */
    @java.lang.Override
    public /* nullable */
com.bragi.LolTeamCurrentMapState getTeamsOrDefault(
        java.lang.String key,
        /* nullable */
com.bragi.LolTeamCurrentMapState defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.bragi.LolTeamCurrentMapStateOrBuilder> map = internalGetMutableTeams().ensureBuilderMap();
      return map.containsKey(key) ? teamsConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .bragi.LolTeamCurrentMapState&gt; teams = 4 [json_name = "teams"];</code>
     */
    @java.lang.Override
    public com.bragi.LolTeamCurrentMapState getTeamsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.bragi.LolTeamCurrentMapStateOrBuilder> map = internalGetMutableTeams().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return teamsConverter.build(map.get(key));
    }
    public Builder clearTeams() {
      bitField0_ = (bitField0_ & ~0x00000008);
      internalGetMutableTeams().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .bragi.LolTeamCurrentMapState&gt; teams = 4 [json_name = "teams"];</code>
     */
    public Builder removeTeams(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableTeams().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.bragi.LolTeamCurrentMapState>
        getMutableTeams() {
      bitField0_ |= 0x00000008;
      return internalGetMutableTeams().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .bragi.LolTeamCurrentMapState&gt; teams = 4 [json_name = "teams"];</code>
     */
    public Builder putTeams(
        java.lang.String key,
        com.bragi.LolTeamCurrentMapState value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableTeams().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>map&lt;string, .bragi.LolTeamCurrentMapState&gt; teams = 4 [json_name = "teams"];</code>
     */
    public Builder putAllTeams(
        java.util.Map<java.lang.String, com.bragi.LolTeamCurrentMapState> values) {
      for (java.util.Map.Entry<java.lang.String, com.bragi.LolTeamCurrentMapState> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableTeams().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>map&lt;string, .bragi.LolTeamCurrentMapState&gt; teams = 4 [json_name = "teams"];</code>
     */
    public com.bragi.LolTeamCurrentMapState.Builder putTeamsBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.bragi.LolTeamCurrentMapStateOrBuilder> builderMap = internalGetMutableTeams().ensureBuilderMap();
      com.bragi.LolTeamCurrentMapStateOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.bragi.LolTeamCurrentMapState.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.bragi.LolTeamCurrentMapState) {
        entry = ((com.bragi.LolTeamCurrentMapState) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.bragi.LolTeamCurrentMapState.Builder) entry;
    }

    private com.bragi.LolTurrets turrets_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.LolTurrets, com.bragi.LolTurrets.Builder, com.bragi.LolTurretsOrBuilder> turretsBuilder_;
    /**
     * <code>.bragi.LolTurrets turrets = 5 [json_name = "turrets"];</code>
     * @return Whether the turrets field is set.
     */
    public boolean hasTurrets() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.bragi.LolTurrets turrets = 5 [json_name = "turrets"];</code>
     * @return The turrets.
     */
    public com.bragi.LolTurrets getTurrets() {
      if (turretsBuilder_ == null) {
        return turrets_ == null ? com.bragi.LolTurrets.getDefaultInstance() : turrets_;
      } else {
        return turretsBuilder_.getMessage();
      }
    }
    /**
     * <code>.bragi.LolTurrets turrets = 5 [json_name = "turrets"];</code>
     */
    public Builder setTurrets(com.bragi.LolTurrets value) {
      if (turretsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        turrets_ = value;
      } else {
        turretsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.LolTurrets turrets = 5 [json_name = "turrets"];</code>
     */
    public Builder setTurrets(
        com.bragi.LolTurrets.Builder builderForValue) {
      if (turretsBuilder_ == null) {
        turrets_ = builderForValue.build();
      } else {
        turretsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.LolTurrets turrets = 5 [json_name = "turrets"];</code>
     */
    public Builder mergeTurrets(com.bragi.LolTurrets value) {
      if (turretsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          turrets_ != null &&
          turrets_ != com.bragi.LolTurrets.getDefaultInstance()) {
          getTurretsBuilder().mergeFrom(value);
        } else {
          turrets_ = value;
        }
      } else {
        turretsBuilder_.mergeFrom(value);
      }
      if (turrets_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.bragi.LolTurrets turrets = 5 [json_name = "turrets"];</code>
     */
    public Builder clearTurrets() {
      bitField0_ = (bitField0_ & ~0x00000010);
      turrets_ = null;
      if (turretsBuilder_ != null) {
        turretsBuilder_.dispose();
        turretsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.LolTurrets turrets = 5 [json_name = "turrets"];</code>
     */
    public com.bragi.LolTurrets.Builder getTurretsBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getTurretsFieldBuilder().getBuilder();
    }
    /**
     * <code>.bragi.LolTurrets turrets = 5 [json_name = "turrets"];</code>
     */
    public com.bragi.LolTurretsOrBuilder getTurretsOrBuilder() {
      if (turretsBuilder_ != null) {
        return turretsBuilder_.getMessageOrBuilder();
      } else {
        return turrets_ == null ?
            com.bragi.LolTurrets.getDefaultInstance() : turrets_;
      }
    }
    /**
     * <code>.bragi.LolTurrets turrets = 5 [json_name = "turrets"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.LolTurrets, com.bragi.LolTurrets.Builder, com.bragi.LolTurretsOrBuilder> 
        getTurretsFieldBuilder() {
      if (turretsBuilder_ == null) {
        turretsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bragi.LolTurrets, com.bragi.LolTurrets.Builder, com.bragi.LolTurretsOrBuilder>(
                getTurrets(),
                getParentForChildren(),
                isClean());
        turrets_ = null;
      }
      return turretsBuilder_;
    }

    private com.bragi.LolInhibitors inhibitors_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.LolInhibitors, com.bragi.LolInhibitors.Builder, com.bragi.LolInhibitorsOrBuilder> inhibitorsBuilder_;
    /**
     * <code>.bragi.LolInhibitors inhibitors = 6 [json_name = "inhibitors"];</code>
     * @return Whether the inhibitors field is set.
     */
    public boolean hasInhibitors() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.bragi.LolInhibitors inhibitors = 6 [json_name = "inhibitors"];</code>
     * @return The inhibitors.
     */
    public com.bragi.LolInhibitors getInhibitors() {
      if (inhibitorsBuilder_ == null) {
        return inhibitors_ == null ? com.bragi.LolInhibitors.getDefaultInstance() : inhibitors_;
      } else {
        return inhibitorsBuilder_.getMessage();
      }
    }
    /**
     * <code>.bragi.LolInhibitors inhibitors = 6 [json_name = "inhibitors"];</code>
     */
    public Builder setInhibitors(com.bragi.LolInhibitors value) {
      if (inhibitorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        inhibitors_ = value;
      } else {
        inhibitorsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.LolInhibitors inhibitors = 6 [json_name = "inhibitors"];</code>
     */
    public Builder setInhibitors(
        com.bragi.LolInhibitors.Builder builderForValue) {
      if (inhibitorsBuilder_ == null) {
        inhibitors_ = builderForValue.build();
      } else {
        inhibitorsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.LolInhibitors inhibitors = 6 [json_name = "inhibitors"];</code>
     */
    public Builder mergeInhibitors(com.bragi.LolInhibitors value) {
      if (inhibitorsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          inhibitors_ != null &&
          inhibitors_ != com.bragi.LolInhibitors.getDefaultInstance()) {
          getInhibitorsBuilder().mergeFrom(value);
        } else {
          inhibitors_ = value;
        }
      } else {
        inhibitorsBuilder_.mergeFrom(value);
      }
      if (inhibitors_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.bragi.LolInhibitors inhibitors = 6 [json_name = "inhibitors"];</code>
     */
    public Builder clearInhibitors() {
      bitField0_ = (bitField0_ & ~0x00000020);
      inhibitors_ = null;
      if (inhibitorsBuilder_ != null) {
        inhibitorsBuilder_.dispose();
        inhibitorsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.LolInhibitors inhibitors = 6 [json_name = "inhibitors"];</code>
     */
    public com.bragi.LolInhibitors.Builder getInhibitorsBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getInhibitorsFieldBuilder().getBuilder();
    }
    /**
     * <code>.bragi.LolInhibitors inhibitors = 6 [json_name = "inhibitors"];</code>
     */
    public com.bragi.LolInhibitorsOrBuilder getInhibitorsOrBuilder() {
      if (inhibitorsBuilder_ != null) {
        return inhibitorsBuilder_.getMessageOrBuilder();
      } else {
        return inhibitors_ == null ?
            com.bragi.LolInhibitors.getDefaultInstance() : inhibitors_;
      }
    }
    /**
     * <code>.bragi.LolInhibitors inhibitors = 6 [json_name = "inhibitors"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.LolInhibitors, com.bragi.LolInhibitors.Builder, com.bragi.LolInhibitorsOrBuilder> 
        getInhibitorsFieldBuilder() {
      if (inhibitorsBuilder_ == null) {
        inhibitorsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bragi.LolInhibitors, com.bragi.LolInhibitors.Builder, com.bragi.LolInhibitorsOrBuilder>(
                getInhibitors(),
                getParentForChildren(),
                isClean());
        inhibitors_ = null;
      }
      return inhibitorsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:bragi.LolCurrentMapState)
  }

  // @@protoc_insertion_point(class_scope:bragi.LolCurrentMapState)
  private static final com.bragi.LolCurrentMapState DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bragi.LolCurrentMapState();
  }

  public static com.bragi.LolCurrentMapState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LolCurrentMapState>
      PARSER = new com.google.protobuf.AbstractParser<LolCurrentMapState>() {
    @java.lang.Override
    public LolCurrentMapState parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LolCurrentMapState> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LolCurrentMapState> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bragi.LolCurrentMapState getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

