// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/lol.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

public interface LolCurrentMapTimeStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bragi.LolCurrentMapTimeState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Duration game_time = 1 [json_name = "gameTime"];</code>
   * @return Whether the gameTime field is set.
   */
  boolean hasGameTime();
  /**
   * <code>.google.protobuf.Duration game_time = 1 [json_name = "gameTime"];</code>
   * @return The gameTime.
   */
  com.google.protobuf.Duration getGameTime();
  /**
   * <code>.google.protobuf.Duration game_time = 1 [json_name = "gameTime"];</code>
   */
  com.google.protobuf.DurationOrBuilder getGameTimeOrBuilder();
}
