// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/lol.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

public interface LolMatchUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bragi.LolMatchUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bragi.LolMatchUpdate.Payload payload = 1 [json_name = "payload"];</code>
   * @return Whether the payload field is set.
   */
  boolean hasPayload();
  /**
   * <code>.bragi.LolMatchUpdate.Payload payload = 1 [json_name = "payload"];</code>
   * @return The payload.
   */
  com.bragi.LolMatchUpdate.Payload getPayload();
  /**
   * <code>.bragi.LolMatchUpdate.Payload payload = 1 [json_name = "payload"];</code>
   */
  com.bragi.LolMatchUpdate.PayloadOrBuilder getPayloadOrBuilder();
}
