// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/lol.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

public interface LolMatchStatePartialUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bragi.LolMatchStatePartialUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Replaces "score" property in LolMatchState.
   * </pre>
   *
   * <code>.bragi.LolMatchScoreState score = 1 [json_name = "score"];</code>
   * @return Whether the score field is set.
   */
  boolean hasScore();
  /**
   * <pre>
   * Replaces "score" property in LolMatchState.
   * </pre>
   *
   * <code>.bragi.LolMatchScoreState score = 1 [json_name = "score"];</code>
   * @return The score.
   */
  com.bragi.LolMatchScoreState getScore();
  /**
   * <pre>
   * Replaces "score" property in LolMatchState.
   * </pre>
   *
   * <code>.bragi.LolMatchScoreState score = 1 [json_name = "score"];</code>
   */
  com.bragi.LolMatchScoreStateOrBuilder getScoreOrBuilder();

  /**
   * <pre>
   * Replaces "current_map_state" property in LolMatchState. To minimalize issues with incorrect updates application
   * on current_map_state, server sends LolMatchStatePartialUpdate with LolMapState in periodic time set by customer.
   * </pre>
   *
   * <code>.bragi.LolCurrentMapState current_map_state = 2 [json_name = "currentMapState"];</code>
   * @return Whether the currentMapState field is set.
   */
  boolean hasCurrentMapState();
  /**
   * <pre>
   * Replaces "current_map_state" property in LolMatchState. To minimalize issues with incorrect updates application
   * on current_map_state, server sends LolMatchStatePartialUpdate with LolMapState in periodic time set by customer.
   * </pre>
   *
   * <code>.bragi.LolCurrentMapState current_map_state = 2 [json_name = "currentMapState"];</code>
   * @return The currentMapState.
   */
  com.bragi.LolCurrentMapState getCurrentMapState();
  /**
   * <pre>
   * Replaces "current_map_state" property in LolMatchState. To minimalize issues with incorrect updates application
   * on current_map_state, server sends LolMatchStatePartialUpdate with LolMapState in periodic time set by customer.
   * </pre>
   *
   * <code>.bragi.LolCurrentMapState current_map_state = 2 [json_name = "currentMapState"];</code>
   */
  com.bragi.LolCurrentMapStateOrBuilder getCurrentMapStateOrBuilder();

  /**
   * <pre>
   * Apply partial update on "current_map_state" property in LolMapState.
   * </pre>
   *
   * <code>.bragi.LolCurrentMapStatePartialUpdate current_map_state_partial_update = 3 [json_name = "currentMapStatePartialUpdate"];</code>
   * @return Whether the currentMapStatePartialUpdate field is set.
   */
  boolean hasCurrentMapStatePartialUpdate();
  /**
   * <pre>
   * Apply partial update on "current_map_state" property in LolMapState.
   * </pre>
   *
   * <code>.bragi.LolCurrentMapStatePartialUpdate current_map_state_partial_update = 3 [json_name = "currentMapStatePartialUpdate"];</code>
   * @return The currentMapStatePartialUpdate.
   */
  com.bragi.LolCurrentMapStatePartialUpdate getCurrentMapStatePartialUpdate();
  /**
   * <pre>
   * Apply partial update on "current_map_state" property in LolMapState.
   * </pre>
   *
   * <code>.bragi.LolCurrentMapStatePartialUpdate current_map_state_partial_update = 3 [json_name = "currentMapStatePartialUpdate"];</code>
   */
  com.bragi.LolCurrentMapStatePartialUpdateOrBuilder getCurrentMapStatePartialUpdateOrBuilder();

  com.bragi.LolMatchStatePartialUpdate.UpdateCase getUpdateCase();
}
