// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/bragi_service.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

public interface MatchTimelineFeedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bragi.MatchTimelineFeedRequest)
    com.google.protobuf.MessageOrBuilder {
}
