// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/rush_basketball.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

public interface RushBasketballCurrentMapStatePartialUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bragi.RushBasketballCurrentMapStatePartialUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Replaces "game_time" property in RushBasketballCurrentMapState.
   * </pre>
   *
   * <code>.bragi.RushBasketballCurrentMapTimeState game_time = 1 [json_name = "gameTime"];</code>
   * @return Whether the gameTime field is set.
   */
  boolean hasGameTime();
  /**
   * <pre>
   * Replaces "game_time" property in RushBasketballCurrentMapState.
   * </pre>
   *
   * <code>.bragi.RushBasketballCurrentMapTimeState game_time = 1 [json_name = "gameTime"];</code>
   * @return The gameTime.
   */
  com.bragi.RushBasketballCurrentMapTimeState getGameTime();
  /**
   * <pre>
   * Replaces "game_time" property in RushBasketballCurrentMapState.
   * </pre>
   *
   * <code>.bragi.RushBasketballCurrentMapTimeState game_time = 1 [json_name = "gameTime"];</code>
   */
  com.bragi.RushBasketballCurrentMapTimeStateOrBuilder getGameTimeOrBuilder();

  /**
   * <pre>
   * Replaces "score" property in RushSoccerCurrentMapState.
   * </pre>
   *
   * <code>.bragi.RushBasketballCurrentMapScoreState score = 2 [json_name = "score"];</code>
   * @return Whether the score field is set.
   */
  boolean hasScore();
  /**
   * <pre>
   * Replaces "score" property in RushSoccerCurrentMapState.
   * </pre>
   *
   * <code>.bragi.RushBasketballCurrentMapScoreState score = 2 [json_name = "score"];</code>
   * @return The score.
   */
  com.bragi.RushBasketballCurrentMapScoreState getScore();
  /**
   * <pre>
   * Replaces "score" property in RushSoccerCurrentMapState.
   * </pre>
   *
   * <code>.bragi.RushBasketballCurrentMapScoreState score = 2 [json_name = "score"];</code>
   */
  com.bragi.RushBasketballCurrentMapScoreStateOrBuilder getScoreOrBuilder();

  /**
   * <pre>
   * Replaces whole value under given key in teams map property in RushBasketballTeamCurrentMapState.
   * </pre>
   *
   * <code>.bragi.RushBasketballTeamCurrentMapState team_current_map_state = 3 [json_name = "teamCurrentMapState"];</code>
   * @return Whether the teamCurrentMapState field is set.
   */
  boolean hasTeamCurrentMapState();
  /**
   * <pre>
   * Replaces whole value under given key in teams map property in RushBasketballTeamCurrentMapState.
   * </pre>
   *
   * <code>.bragi.RushBasketballTeamCurrentMapState team_current_map_state = 3 [json_name = "teamCurrentMapState"];</code>
   * @return The teamCurrentMapState.
   */
  com.bragi.RushBasketballTeamCurrentMapState getTeamCurrentMapState();
  /**
   * <pre>
   * Replaces whole value under given key in teams map property in RushBasketballTeamCurrentMapState.
   * </pre>
   *
   * <code>.bragi.RushBasketballTeamCurrentMapState team_current_map_state = 3 [json_name = "teamCurrentMapState"];</code>
   */
  com.bragi.RushBasketballTeamCurrentMapStateOrBuilder getTeamCurrentMapStateOrBuilder();

  /**
   * <pre>
   * Apply partial update on value under given key in teams map property in RushBasketballCurrentMapState.
   * </pre>
   *
   * <code>.bragi.RushBasketballTeamCurrentMapStatePartialUpdate team_current_map_partial_update = 4 [json_name = "teamCurrentMapPartialUpdate"];</code>
   * @return Whether the teamCurrentMapPartialUpdate field is set.
   */
  boolean hasTeamCurrentMapPartialUpdate();
  /**
   * <pre>
   * Apply partial update on value under given key in teams map property in RushBasketballCurrentMapState.
   * </pre>
   *
   * <code>.bragi.RushBasketballTeamCurrentMapStatePartialUpdate team_current_map_partial_update = 4 [json_name = "teamCurrentMapPartialUpdate"];</code>
   * @return The teamCurrentMapPartialUpdate.
   */
  com.bragi.RushBasketballTeamCurrentMapStatePartialUpdate getTeamCurrentMapPartialUpdate();
  /**
   * <pre>
   * Apply partial update on value under given key in teams map property in RushBasketballCurrentMapState.
   * </pre>
   *
   * <code>.bragi.RushBasketballTeamCurrentMapStatePartialUpdate team_current_map_partial_update = 4 [json_name = "teamCurrentMapPartialUpdate"];</code>
   */
  com.bragi.RushBasketballTeamCurrentMapStatePartialUpdateOrBuilder getTeamCurrentMapPartialUpdateOrBuilder();

  com.bragi.RushBasketballCurrentMapStatePartialUpdate.UpdateCase getUpdateCase();
}
