// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/rush_basketball.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

/**
 * Protobuf enum {@code bragi.RushBasketballPeriod}
 */
public enum RushBasketballPeriod
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>RUSH_BASKETBALL_PERIOD_UNSPECIFIED = 0;</code>
   */
  RUSH_BASKETBALL_PERIOD_UNSPECIFIED(0),
  /**
   * <code>RUSH_BASKETBALL_PERIOD_QUARTER_1 = 1;</code>
   */
  RUSH_BASKETBALL_PERIOD_QUARTER_1(1),
  /**
   * <code>RUSH_BASKETBALL_PERIOD_QUARTER_2 = 2;</code>
   */
  RUSH_BASKETBALL_PERIOD_QUARTER_2(2),
  /**
   * <code>RUSH_BASKETBALL_PERIOD_QUARTER_3 = 3;</code>
   */
  RUSH_BASKETBALL_PERIOD_QUARTER_3(3),
  /**
   * <code>RUSH_BASKETBALL_PERIOD_QUARTER_4 = 4;</code>
   */
  RUSH_BASKETBALL_PERIOD_QUARTER_4(4),
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME = 5 [deprecated = true];</code>
   */
  @java.lang.Deprecated
  RUSH_BASKETBALL_PERIOD_OVERTIME(5),
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_1 = 6;</code>
   */
  RUSH_BASKETBALL_PERIOD_OVERTIME_1(6),
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_2 = 7;</code>
   */
  RUSH_BASKETBALL_PERIOD_OVERTIME_2(7),
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_3 = 8;</code>
   */
  RUSH_BASKETBALL_PERIOD_OVERTIME_3(8),
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_4 = 9;</code>
   */
  RUSH_BASKETBALL_PERIOD_OVERTIME_4(9),
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_5 = 10;</code>
   */
  RUSH_BASKETBALL_PERIOD_OVERTIME_5(10),
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_6 = 11;</code>
   */
  RUSH_BASKETBALL_PERIOD_OVERTIME_6(11),
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_7 = 12;</code>
   */
  RUSH_BASKETBALL_PERIOD_OVERTIME_7(12),
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_8 = 13;</code>
   */
  RUSH_BASKETBALL_PERIOD_OVERTIME_8(13),
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_9 = 14;</code>
   */
  RUSH_BASKETBALL_PERIOD_OVERTIME_9(14),
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_10 = 16;</code>
   */
  RUSH_BASKETBALL_PERIOD_OVERTIME_10(16),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      RushBasketballPeriod.class.getName());
  }
  /**
   * <code>RUSH_BASKETBALL_PERIOD_UNSPECIFIED = 0;</code>
   */
  public static final int RUSH_BASKETBALL_PERIOD_UNSPECIFIED_VALUE = 0;
  /**
   * <code>RUSH_BASKETBALL_PERIOD_QUARTER_1 = 1;</code>
   */
  public static final int RUSH_BASKETBALL_PERIOD_QUARTER_1_VALUE = 1;
  /**
   * <code>RUSH_BASKETBALL_PERIOD_QUARTER_2 = 2;</code>
   */
  public static final int RUSH_BASKETBALL_PERIOD_QUARTER_2_VALUE = 2;
  /**
   * <code>RUSH_BASKETBALL_PERIOD_QUARTER_3 = 3;</code>
   */
  public static final int RUSH_BASKETBALL_PERIOD_QUARTER_3_VALUE = 3;
  /**
   * <code>RUSH_BASKETBALL_PERIOD_QUARTER_4 = 4;</code>
   */
  public static final int RUSH_BASKETBALL_PERIOD_QUARTER_4_VALUE = 4;
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME = 5 [deprecated = true];</code>
   */
  @java.lang.Deprecated public static final int RUSH_BASKETBALL_PERIOD_OVERTIME_VALUE = 5;
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_1 = 6;</code>
   */
  public static final int RUSH_BASKETBALL_PERIOD_OVERTIME_1_VALUE = 6;
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_2 = 7;</code>
   */
  public static final int RUSH_BASKETBALL_PERIOD_OVERTIME_2_VALUE = 7;
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_3 = 8;</code>
   */
  public static final int RUSH_BASKETBALL_PERIOD_OVERTIME_3_VALUE = 8;
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_4 = 9;</code>
   */
  public static final int RUSH_BASKETBALL_PERIOD_OVERTIME_4_VALUE = 9;
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_5 = 10;</code>
   */
  public static final int RUSH_BASKETBALL_PERIOD_OVERTIME_5_VALUE = 10;
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_6 = 11;</code>
   */
  public static final int RUSH_BASKETBALL_PERIOD_OVERTIME_6_VALUE = 11;
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_7 = 12;</code>
   */
  public static final int RUSH_BASKETBALL_PERIOD_OVERTIME_7_VALUE = 12;
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_8 = 13;</code>
   */
  public static final int RUSH_BASKETBALL_PERIOD_OVERTIME_8_VALUE = 13;
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_9 = 14;</code>
   */
  public static final int RUSH_BASKETBALL_PERIOD_OVERTIME_9_VALUE = 14;
  /**
   * <code>RUSH_BASKETBALL_PERIOD_OVERTIME_10 = 16;</code>
   */
  public static final int RUSH_BASKETBALL_PERIOD_OVERTIME_10_VALUE = 16;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RushBasketballPeriod valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RushBasketballPeriod forNumber(int value) {
    switch (value) {
      case 0: return RUSH_BASKETBALL_PERIOD_UNSPECIFIED;
      case 1: return RUSH_BASKETBALL_PERIOD_QUARTER_1;
      case 2: return RUSH_BASKETBALL_PERIOD_QUARTER_2;
      case 3: return RUSH_BASKETBALL_PERIOD_QUARTER_3;
      case 4: return RUSH_BASKETBALL_PERIOD_QUARTER_4;
      case 5: return RUSH_BASKETBALL_PERIOD_OVERTIME;
      case 6: return RUSH_BASKETBALL_PERIOD_OVERTIME_1;
      case 7: return RUSH_BASKETBALL_PERIOD_OVERTIME_2;
      case 8: return RUSH_BASKETBALL_PERIOD_OVERTIME_3;
      case 9: return RUSH_BASKETBALL_PERIOD_OVERTIME_4;
      case 10: return RUSH_BASKETBALL_PERIOD_OVERTIME_5;
      case 11: return RUSH_BASKETBALL_PERIOD_OVERTIME_6;
      case 12: return RUSH_BASKETBALL_PERIOD_OVERTIME_7;
      case 13: return RUSH_BASKETBALL_PERIOD_OVERTIME_8;
      case 14: return RUSH_BASKETBALL_PERIOD_OVERTIME_9;
      case 16: return RUSH_BASKETBALL_PERIOD_OVERTIME_10;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RushBasketballPeriod>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RushBasketballPeriod> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RushBasketballPeriod>() {
          public RushBasketballPeriod findValueByNumber(int number) {
            return RushBasketballPeriod.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.bragi.RushBasketballProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final RushBasketballPeriod[] VALUES = values();

  public static RushBasketballPeriod valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RushBasketballPeriod(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:bragi.RushBasketballPeriod)
}

