// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/valorant.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

/**
 * Protobuf type {@code bragi.ValorantCurrentMapState}
 */
public final class ValorantCurrentMapState extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:bragi.ValorantCurrentMapState)
    ValorantCurrentMapStateOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ValorantCurrentMapState.class.getName());
  }
  // Use ValorantCurrentMapState.newBuilder() to construct.
  private ValorantCurrentMapState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ValorantCurrentMapState() {
    mapName_ = "";
    winTeamUrn_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bragi.ValorantProto.internal_static_bragi_ValorantCurrentMapState_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 7:
        return internalGetTeams();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bragi.ValorantProto.internal_static_bragi_ValorantCurrentMapState_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bragi.ValorantCurrentMapState.class, com.bragi.ValorantCurrentMapState.Builder.class);
  }

  private int bitField0_;
  public static final int MAP_ORDER_FIELD_NUMBER = 1;
  private int mapOrder_ = 0;
  /**
   * <code>uint32 map_order = 1 [json_name = "mapOrder"];</code>
   * @return The mapOrder.
   */
  @java.lang.Override
  public int getMapOrder() {
    return mapOrder_;
  }

  public static final int MAP_PAUSED_FIELD_NUMBER = 2;
  private boolean mapPaused_ = false;
  /**
   * <code>bool map_paused = 2 [json_name = "mapPaused"];</code>
   * @return The mapPaused.
   */
  @java.lang.Override
  public boolean getMapPaused() {
    return mapPaused_;
  }

  public static final int MAP_NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object mapName_ = "";
  /**
   * <code>string map_name = 3 [json_name = "mapName"];</code>
   * @return The mapName.
   */
  @java.lang.Override
  public java.lang.String getMapName() {
    java.lang.Object ref = mapName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mapName_ = s;
      return s;
    }
  }
  /**
   * <code>string map_name = 3 [json_name = "mapName"];</code>
   * @return The bytes for mapName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMapNameBytes() {
    java.lang.Object ref = mapName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mapName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WIN_TEAM_URN_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object winTeamUrn_ = "";
  /**
   * <code>optional string win_team_urn = 4 [json_name = "winTeamUrn"];</code>
   * @return Whether the winTeamUrn field is set.
   */
  @java.lang.Override
  public boolean hasWinTeamUrn() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string win_team_urn = 4 [json_name = "winTeamUrn"];</code>
   * @return The winTeamUrn.
   */
  @java.lang.Override
  public java.lang.String getWinTeamUrn() {
    java.lang.Object ref = winTeamUrn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      winTeamUrn_ = s;
      return s;
    }
  }
  /**
   * <code>optional string win_team_urn = 4 [json_name = "winTeamUrn"];</code>
   * @return The bytes for winTeamUrn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWinTeamUrnBytes() {
    java.lang.Object ref = winTeamUrn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      winTeamUrn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCORE_FIELD_NUMBER = 5;
  private com.bragi.ValorantMapScoreState score_;
  /**
   * <code>.bragi.ValorantMapScoreState score = 5 [json_name = "score"];</code>
   * @return Whether the score field is set.
   */
  @java.lang.Override
  public boolean hasScore() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.bragi.ValorantMapScoreState score = 5 [json_name = "score"];</code>
   * @return The score.
   */
  @java.lang.Override
  public com.bragi.ValorantMapScoreState getScore() {
    return score_ == null ? com.bragi.ValorantMapScoreState.getDefaultInstance() : score_;
  }
  /**
   * <code>.bragi.ValorantMapScoreState score = 5 [json_name = "score"];</code>
   */
  @java.lang.Override
  public com.bragi.ValorantMapScoreStateOrBuilder getScoreOrBuilder() {
    return score_ == null ? com.bragi.ValorantMapScoreState.getDefaultInstance() : score_;
  }

  public static final int CURRENT_ROUND_FIELD_NUMBER = 6;
  private com.bragi.ValorantCurrentRoundState currentRound_;
  /**
   * <code>.bragi.ValorantCurrentRoundState current_round = 6 [json_name = "currentRound"];</code>
   * @return Whether the currentRound field is set.
   */
  @java.lang.Override
  public boolean hasCurrentRound() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.bragi.ValorantCurrentRoundState current_round = 6 [json_name = "currentRound"];</code>
   * @return The currentRound.
   */
  @java.lang.Override
  public com.bragi.ValorantCurrentRoundState getCurrentRound() {
    return currentRound_ == null ? com.bragi.ValorantCurrentRoundState.getDefaultInstance() : currentRound_;
  }
  /**
   * <code>.bragi.ValorantCurrentRoundState current_round = 6 [json_name = "currentRound"];</code>
   */
  @java.lang.Override
  public com.bragi.ValorantCurrentRoundStateOrBuilder getCurrentRoundOrBuilder() {
    return currentRound_ == null ? com.bragi.ValorantCurrentRoundState.getDefaultInstance() : currentRound_;
  }

  public static final int TEAMS_FIELD_NUMBER = 7;
  private static final class TeamsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.bragi.ValorantTeamCurrentMapState> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.bragi.ValorantTeamCurrentMapState>newDefaultInstance(
                com.bragi.ValorantProto.internal_static_bragi_ValorantCurrentMapState_TeamsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.bragi.ValorantTeamCurrentMapState.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.bragi.ValorantTeamCurrentMapState> teams_;
  private com.google.protobuf.MapField<java.lang.String, com.bragi.ValorantTeamCurrentMapState>
  internalGetTeams() {
    if (teams_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TeamsDefaultEntryHolder.defaultEntry);
    }
    return teams_;
  }
  public int getTeamsCount() {
    return internalGetTeams().getMap().size();
  }
  /**
   * <code>map&lt;string, .bragi.ValorantTeamCurrentMapState&gt; teams = 7 [json_name = "teams"];</code>
   */
  @java.lang.Override
  public boolean containsTeams(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetTeams().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTeamsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.bragi.ValorantTeamCurrentMapState> getTeams() {
    return getTeamsMap();
  }
  /**
   * <code>map&lt;string, .bragi.ValorantTeamCurrentMapState&gt; teams = 7 [json_name = "teams"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.bragi.ValorantTeamCurrentMapState> getTeamsMap() {
    return internalGetTeams().getMap();
  }
  /**
   * <code>map&lt;string, .bragi.ValorantTeamCurrentMapState&gt; teams = 7 [json_name = "teams"];</code>
   */
  @java.lang.Override
  public /* nullable */
com.bragi.ValorantTeamCurrentMapState getTeamsOrDefault(
      java.lang.String key,
      /* nullable */
com.bragi.ValorantTeamCurrentMapState defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.bragi.ValorantTeamCurrentMapState> map =
        internalGetTeams().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .bragi.ValorantTeamCurrentMapState&gt; teams = 7 [json_name = "teams"];</code>
   */
  @java.lang.Override
  public com.bragi.ValorantTeamCurrentMapState getTeamsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.bragi.ValorantTeamCurrentMapState> map =
        internalGetTeams().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int PREVIOUS_ROUNDS_FIELD_NUMBER = 8;
  private com.bragi.ValorantPreviousRoundsState previousRounds_;
  /**
   * <code>.bragi.ValorantPreviousRoundsState previous_rounds = 8 [json_name = "previousRounds"];</code>
   * @return Whether the previousRounds field is set.
   */
  @java.lang.Override
  public boolean hasPreviousRounds() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.bragi.ValorantPreviousRoundsState previous_rounds = 8 [json_name = "previousRounds"];</code>
   * @return The previousRounds.
   */
  @java.lang.Override
  public com.bragi.ValorantPreviousRoundsState getPreviousRounds() {
    return previousRounds_ == null ? com.bragi.ValorantPreviousRoundsState.getDefaultInstance() : previousRounds_;
  }
  /**
   * <code>.bragi.ValorantPreviousRoundsState previous_rounds = 8 [json_name = "previousRounds"];</code>
   */
  @java.lang.Override
  public com.bragi.ValorantPreviousRoundsStateOrBuilder getPreviousRoundsOrBuilder() {
    return previousRounds_ == null ? com.bragi.ValorantPreviousRoundsState.getDefaultInstance() : previousRounds_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (mapOrder_ != 0) {
      output.writeUInt32(1, mapOrder_);
    }
    if (mapPaused_ != false) {
      output.writeBool(2, mapPaused_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mapName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, mapName_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, winTeamUrn_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getScore());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(6, getCurrentRound());
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetTeams(),
        TeamsDefaultEntryHolder.defaultEntry,
        7);
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(8, getPreviousRounds());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mapOrder_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, mapOrder_);
    }
    if (mapPaused_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, mapPaused_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mapName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, mapName_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, winTeamUrn_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getScore());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getCurrentRound());
    }
    for (java.util.Map.Entry<java.lang.String, com.bragi.ValorantTeamCurrentMapState> entry
         : internalGetTeams().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.bragi.ValorantTeamCurrentMapState>
      teams__ = TeamsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, teams__);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getPreviousRounds());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bragi.ValorantCurrentMapState)) {
      return super.equals(obj);
    }
    com.bragi.ValorantCurrentMapState other = (com.bragi.ValorantCurrentMapState) obj;

    if (getMapOrder()
        != other.getMapOrder()) return false;
    if (getMapPaused()
        != other.getMapPaused()) return false;
    if (!getMapName()
        .equals(other.getMapName())) return false;
    if (hasWinTeamUrn() != other.hasWinTeamUrn()) return false;
    if (hasWinTeamUrn()) {
      if (!getWinTeamUrn()
          .equals(other.getWinTeamUrn())) return false;
    }
    if (hasScore() != other.hasScore()) return false;
    if (hasScore()) {
      if (!getScore()
          .equals(other.getScore())) return false;
    }
    if (hasCurrentRound() != other.hasCurrentRound()) return false;
    if (hasCurrentRound()) {
      if (!getCurrentRound()
          .equals(other.getCurrentRound())) return false;
    }
    if (!internalGetTeams().equals(
        other.internalGetTeams())) return false;
    if (hasPreviousRounds() != other.hasPreviousRounds()) return false;
    if (hasPreviousRounds()) {
      if (!getPreviousRounds()
          .equals(other.getPreviousRounds())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAP_ORDER_FIELD_NUMBER;
    hash = (53 * hash) + getMapOrder();
    hash = (37 * hash) + MAP_PAUSED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMapPaused());
    hash = (37 * hash) + MAP_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getMapName().hashCode();
    if (hasWinTeamUrn()) {
      hash = (37 * hash) + WIN_TEAM_URN_FIELD_NUMBER;
      hash = (53 * hash) + getWinTeamUrn().hashCode();
    }
    if (hasScore()) {
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + getScore().hashCode();
    }
    if (hasCurrentRound()) {
      hash = (37 * hash) + CURRENT_ROUND_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentRound().hashCode();
    }
    if (!internalGetTeams().getMap().isEmpty()) {
      hash = (37 * hash) + TEAMS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTeams().hashCode();
    }
    if (hasPreviousRounds()) {
      hash = (37 * hash) + PREVIOUS_ROUNDS_FIELD_NUMBER;
      hash = (53 * hash) + getPreviousRounds().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bragi.ValorantCurrentMapState parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.ValorantCurrentMapState parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.ValorantCurrentMapState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.ValorantCurrentMapState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.ValorantCurrentMapState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bragi.ValorantCurrentMapState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bragi.ValorantCurrentMapState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bragi.ValorantCurrentMapState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bragi.ValorantCurrentMapState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bragi.ValorantCurrentMapState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bragi.ValorantCurrentMapState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bragi.ValorantCurrentMapState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bragi.ValorantCurrentMapState prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bragi.ValorantCurrentMapState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bragi.ValorantCurrentMapState)
      com.bragi.ValorantCurrentMapStateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bragi.ValorantProto.internal_static_bragi_ValorantCurrentMapState_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 7:
          return internalGetTeams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 7:
          return internalGetMutableTeams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bragi.ValorantProto.internal_static_bragi_ValorantCurrentMapState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bragi.ValorantCurrentMapState.class, com.bragi.ValorantCurrentMapState.Builder.class);
    }

    // Construct using com.bragi.ValorantCurrentMapState.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getScoreFieldBuilder();
        getCurrentRoundFieldBuilder();
        getPreviousRoundsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      mapOrder_ = 0;
      mapPaused_ = false;
      mapName_ = "";
      winTeamUrn_ = "";
      score_ = null;
      if (scoreBuilder_ != null) {
        scoreBuilder_.dispose();
        scoreBuilder_ = null;
      }
      currentRound_ = null;
      if (currentRoundBuilder_ != null) {
        currentRoundBuilder_.dispose();
        currentRoundBuilder_ = null;
      }
      internalGetMutableTeams().clear();
      previousRounds_ = null;
      if (previousRoundsBuilder_ != null) {
        previousRoundsBuilder_.dispose();
        previousRoundsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bragi.ValorantProto.internal_static_bragi_ValorantCurrentMapState_descriptor;
    }

    @java.lang.Override
    public com.bragi.ValorantCurrentMapState getDefaultInstanceForType() {
      return com.bragi.ValorantCurrentMapState.getDefaultInstance();
    }

    @java.lang.Override
    public com.bragi.ValorantCurrentMapState build() {
      com.bragi.ValorantCurrentMapState result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bragi.ValorantCurrentMapState buildPartial() {
      com.bragi.ValorantCurrentMapState result = new com.bragi.ValorantCurrentMapState(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bragi.ValorantCurrentMapState result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.mapOrder_ = mapOrder_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.mapPaused_ = mapPaused_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.mapName_ = mapName_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.winTeamUrn_ = winTeamUrn_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.score_ = scoreBuilder_ == null
            ? score_
            : scoreBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.currentRound_ = currentRoundBuilder_ == null
            ? currentRound_
            : currentRoundBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.teams_ = internalGetTeams().build(TeamsDefaultEntryHolder.defaultEntry);
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.previousRounds_ = previousRoundsBuilder_ == null
            ? previousRounds_
            : previousRoundsBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bragi.ValorantCurrentMapState) {
        return mergeFrom((com.bragi.ValorantCurrentMapState)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bragi.ValorantCurrentMapState other) {
      if (other == com.bragi.ValorantCurrentMapState.getDefaultInstance()) return this;
      if (other.getMapOrder() != 0) {
        setMapOrder(other.getMapOrder());
      }
      if (other.getMapPaused() != false) {
        setMapPaused(other.getMapPaused());
      }
      if (!other.getMapName().isEmpty()) {
        mapName_ = other.mapName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasWinTeamUrn()) {
        winTeamUrn_ = other.winTeamUrn_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasScore()) {
        mergeScore(other.getScore());
      }
      if (other.hasCurrentRound()) {
        mergeCurrentRound(other.getCurrentRound());
      }
      internalGetMutableTeams().mergeFrom(
          other.internalGetTeams());
      bitField0_ |= 0x00000040;
      if (other.hasPreviousRounds()) {
        mergePreviousRounds(other.getPreviousRounds());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              mapOrder_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              mapPaused_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              mapName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              winTeamUrn_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getScoreFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getCurrentRoundFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              com.google.protobuf.MapEntry<java.lang.String, com.bragi.ValorantTeamCurrentMapState>
              teams__ = input.readMessage(
                  TeamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableTeams().ensureBuilderMap().put(
                  teams__.getKey(), teams__.getValue());
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getPreviousRoundsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int mapOrder_ ;
    /**
     * <code>uint32 map_order = 1 [json_name = "mapOrder"];</code>
     * @return The mapOrder.
     */
    @java.lang.Override
    public int getMapOrder() {
      return mapOrder_;
    }
    /**
     * <code>uint32 map_order = 1 [json_name = "mapOrder"];</code>
     * @param value The mapOrder to set.
     * @return This builder for chaining.
     */
    public Builder setMapOrder(int value) {

      mapOrder_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 map_order = 1 [json_name = "mapOrder"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMapOrder() {
      bitField0_ = (bitField0_ & ~0x00000001);
      mapOrder_ = 0;
      onChanged();
      return this;
    }

    private boolean mapPaused_ ;
    /**
     * <code>bool map_paused = 2 [json_name = "mapPaused"];</code>
     * @return The mapPaused.
     */
    @java.lang.Override
    public boolean getMapPaused() {
      return mapPaused_;
    }
    /**
     * <code>bool map_paused = 2 [json_name = "mapPaused"];</code>
     * @param value The mapPaused to set.
     * @return This builder for chaining.
     */
    public Builder setMapPaused(boolean value) {

      mapPaused_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool map_paused = 2 [json_name = "mapPaused"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMapPaused() {
      bitField0_ = (bitField0_ & ~0x00000002);
      mapPaused_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object mapName_ = "";
    /**
     * <code>string map_name = 3 [json_name = "mapName"];</code>
     * @return The mapName.
     */
    public java.lang.String getMapName() {
      java.lang.Object ref = mapName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mapName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string map_name = 3 [json_name = "mapName"];</code>
     * @return The bytes for mapName.
     */
    public com.google.protobuf.ByteString
        getMapNameBytes() {
      java.lang.Object ref = mapName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mapName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string map_name = 3 [json_name = "mapName"];</code>
     * @param value The mapName to set.
     * @return This builder for chaining.
     */
    public Builder setMapName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      mapName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string map_name = 3 [json_name = "mapName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMapName() {
      mapName_ = getDefaultInstance().getMapName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string map_name = 3 [json_name = "mapName"];</code>
     * @param value The bytes for mapName to set.
     * @return This builder for chaining.
     */
    public Builder setMapNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      mapName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object winTeamUrn_ = "";
    /**
     * <code>optional string win_team_urn = 4 [json_name = "winTeamUrn"];</code>
     * @return Whether the winTeamUrn field is set.
     */
    public boolean hasWinTeamUrn() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string win_team_urn = 4 [json_name = "winTeamUrn"];</code>
     * @return The winTeamUrn.
     */
    public java.lang.String getWinTeamUrn() {
      java.lang.Object ref = winTeamUrn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        winTeamUrn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string win_team_urn = 4 [json_name = "winTeamUrn"];</code>
     * @return The bytes for winTeamUrn.
     */
    public com.google.protobuf.ByteString
        getWinTeamUrnBytes() {
      java.lang.Object ref = winTeamUrn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        winTeamUrn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string win_team_urn = 4 [json_name = "winTeamUrn"];</code>
     * @param value The winTeamUrn to set.
     * @return This builder for chaining.
     */
    public Builder setWinTeamUrn(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      winTeamUrn_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string win_team_urn = 4 [json_name = "winTeamUrn"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWinTeamUrn() {
      winTeamUrn_ = getDefaultInstance().getWinTeamUrn();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string win_team_urn = 4 [json_name = "winTeamUrn"];</code>
     * @param value The bytes for winTeamUrn to set.
     * @return This builder for chaining.
     */
    public Builder setWinTeamUrnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      winTeamUrn_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.bragi.ValorantMapScoreState score_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.ValorantMapScoreState, com.bragi.ValorantMapScoreState.Builder, com.bragi.ValorantMapScoreStateOrBuilder> scoreBuilder_;
    /**
     * <code>.bragi.ValorantMapScoreState score = 5 [json_name = "score"];</code>
     * @return Whether the score field is set.
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.bragi.ValorantMapScoreState score = 5 [json_name = "score"];</code>
     * @return The score.
     */
    public com.bragi.ValorantMapScoreState getScore() {
      if (scoreBuilder_ == null) {
        return score_ == null ? com.bragi.ValorantMapScoreState.getDefaultInstance() : score_;
      } else {
        return scoreBuilder_.getMessage();
      }
    }
    /**
     * <code>.bragi.ValorantMapScoreState score = 5 [json_name = "score"];</code>
     */
    public Builder setScore(com.bragi.ValorantMapScoreState value) {
      if (scoreBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        score_ = value;
      } else {
        scoreBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.ValorantMapScoreState score = 5 [json_name = "score"];</code>
     */
    public Builder setScore(
        com.bragi.ValorantMapScoreState.Builder builderForValue) {
      if (scoreBuilder_ == null) {
        score_ = builderForValue.build();
      } else {
        scoreBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.ValorantMapScoreState score = 5 [json_name = "score"];</code>
     */
    public Builder mergeScore(com.bragi.ValorantMapScoreState value) {
      if (scoreBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          score_ != null &&
          score_ != com.bragi.ValorantMapScoreState.getDefaultInstance()) {
          getScoreBuilder().mergeFrom(value);
        } else {
          score_ = value;
        }
      } else {
        scoreBuilder_.mergeFrom(value);
      }
      if (score_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.bragi.ValorantMapScoreState score = 5 [json_name = "score"];</code>
     */
    public Builder clearScore() {
      bitField0_ = (bitField0_ & ~0x00000010);
      score_ = null;
      if (scoreBuilder_ != null) {
        scoreBuilder_.dispose();
        scoreBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.ValorantMapScoreState score = 5 [json_name = "score"];</code>
     */
    public com.bragi.ValorantMapScoreState.Builder getScoreBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getScoreFieldBuilder().getBuilder();
    }
    /**
     * <code>.bragi.ValorantMapScoreState score = 5 [json_name = "score"];</code>
     */
    public com.bragi.ValorantMapScoreStateOrBuilder getScoreOrBuilder() {
      if (scoreBuilder_ != null) {
        return scoreBuilder_.getMessageOrBuilder();
      } else {
        return score_ == null ?
            com.bragi.ValorantMapScoreState.getDefaultInstance() : score_;
      }
    }
    /**
     * <code>.bragi.ValorantMapScoreState score = 5 [json_name = "score"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.ValorantMapScoreState, com.bragi.ValorantMapScoreState.Builder, com.bragi.ValorantMapScoreStateOrBuilder> 
        getScoreFieldBuilder() {
      if (scoreBuilder_ == null) {
        scoreBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bragi.ValorantMapScoreState, com.bragi.ValorantMapScoreState.Builder, com.bragi.ValorantMapScoreStateOrBuilder>(
                getScore(),
                getParentForChildren(),
                isClean());
        score_ = null;
      }
      return scoreBuilder_;
    }

    private com.bragi.ValorantCurrentRoundState currentRound_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.ValorantCurrentRoundState, com.bragi.ValorantCurrentRoundState.Builder, com.bragi.ValorantCurrentRoundStateOrBuilder> currentRoundBuilder_;
    /**
     * <code>.bragi.ValorantCurrentRoundState current_round = 6 [json_name = "currentRound"];</code>
     * @return Whether the currentRound field is set.
     */
    public boolean hasCurrentRound() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.bragi.ValorantCurrentRoundState current_round = 6 [json_name = "currentRound"];</code>
     * @return The currentRound.
     */
    public com.bragi.ValorantCurrentRoundState getCurrentRound() {
      if (currentRoundBuilder_ == null) {
        return currentRound_ == null ? com.bragi.ValorantCurrentRoundState.getDefaultInstance() : currentRound_;
      } else {
        return currentRoundBuilder_.getMessage();
      }
    }
    /**
     * <code>.bragi.ValorantCurrentRoundState current_round = 6 [json_name = "currentRound"];</code>
     */
    public Builder setCurrentRound(com.bragi.ValorantCurrentRoundState value) {
      if (currentRoundBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        currentRound_ = value;
      } else {
        currentRoundBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.ValorantCurrentRoundState current_round = 6 [json_name = "currentRound"];</code>
     */
    public Builder setCurrentRound(
        com.bragi.ValorantCurrentRoundState.Builder builderForValue) {
      if (currentRoundBuilder_ == null) {
        currentRound_ = builderForValue.build();
      } else {
        currentRoundBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.ValorantCurrentRoundState current_round = 6 [json_name = "currentRound"];</code>
     */
    public Builder mergeCurrentRound(com.bragi.ValorantCurrentRoundState value) {
      if (currentRoundBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          currentRound_ != null &&
          currentRound_ != com.bragi.ValorantCurrentRoundState.getDefaultInstance()) {
          getCurrentRoundBuilder().mergeFrom(value);
        } else {
          currentRound_ = value;
        }
      } else {
        currentRoundBuilder_.mergeFrom(value);
      }
      if (currentRound_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.bragi.ValorantCurrentRoundState current_round = 6 [json_name = "currentRound"];</code>
     */
    public Builder clearCurrentRound() {
      bitField0_ = (bitField0_ & ~0x00000020);
      currentRound_ = null;
      if (currentRoundBuilder_ != null) {
        currentRoundBuilder_.dispose();
        currentRoundBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.ValorantCurrentRoundState current_round = 6 [json_name = "currentRound"];</code>
     */
    public com.bragi.ValorantCurrentRoundState.Builder getCurrentRoundBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getCurrentRoundFieldBuilder().getBuilder();
    }
    /**
     * <code>.bragi.ValorantCurrentRoundState current_round = 6 [json_name = "currentRound"];</code>
     */
    public com.bragi.ValorantCurrentRoundStateOrBuilder getCurrentRoundOrBuilder() {
      if (currentRoundBuilder_ != null) {
        return currentRoundBuilder_.getMessageOrBuilder();
      } else {
        return currentRound_ == null ?
            com.bragi.ValorantCurrentRoundState.getDefaultInstance() : currentRound_;
      }
    }
    /**
     * <code>.bragi.ValorantCurrentRoundState current_round = 6 [json_name = "currentRound"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.ValorantCurrentRoundState, com.bragi.ValorantCurrentRoundState.Builder, com.bragi.ValorantCurrentRoundStateOrBuilder> 
        getCurrentRoundFieldBuilder() {
      if (currentRoundBuilder_ == null) {
        currentRoundBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bragi.ValorantCurrentRoundState, com.bragi.ValorantCurrentRoundState.Builder, com.bragi.ValorantCurrentRoundStateOrBuilder>(
                getCurrentRound(),
                getParentForChildren(),
                isClean());
        currentRound_ = null;
      }
      return currentRoundBuilder_;
    }

    private static final class TeamsConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.bragi.ValorantTeamCurrentMapStateOrBuilder, com.bragi.ValorantTeamCurrentMapState> {
      @java.lang.Override
      public com.bragi.ValorantTeamCurrentMapState build(com.bragi.ValorantTeamCurrentMapStateOrBuilder val) {
        if (val instanceof com.bragi.ValorantTeamCurrentMapState) { return (com.bragi.ValorantTeamCurrentMapState) val; }
        return ((com.bragi.ValorantTeamCurrentMapState.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.bragi.ValorantTeamCurrentMapState> defaultEntry() {
        return TeamsDefaultEntryHolder.defaultEntry;
      }
    };
    private static final TeamsConverter teamsConverter = new TeamsConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.bragi.ValorantTeamCurrentMapStateOrBuilder, com.bragi.ValorantTeamCurrentMapState, com.bragi.ValorantTeamCurrentMapState.Builder> teams_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.bragi.ValorantTeamCurrentMapStateOrBuilder, com.bragi.ValorantTeamCurrentMapState, com.bragi.ValorantTeamCurrentMapState.Builder>
        internalGetTeams() {
      if (teams_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(teamsConverter);
      }
      return teams_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.bragi.ValorantTeamCurrentMapStateOrBuilder, com.bragi.ValorantTeamCurrentMapState, com.bragi.ValorantTeamCurrentMapState.Builder>
        internalGetMutableTeams() {
      if (teams_ == null) {
        teams_ = new com.google.protobuf.MapFieldBuilder<>(teamsConverter);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return teams_;
    }
    public int getTeamsCount() {
      return internalGetTeams().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .bragi.ValorantTeamCurrentMapState&gt; teams = 7 [json_name = "teams"];</code>
     */
    @java.lang.Override
    public boolean containsTeams(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetTeams().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getTeamsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.bragi.ValorantTeamCurrentMapState> getTeams() {
      return getTeamsMap();
    }
    /**
     * <code>map&lt;string, .bragi.ValorantTeamCurrentMapState&gt; teams = 7 [json_name = "teams"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.bragi.ValorantTeamCurrentMapState> getTeamsMap() {
      return internalGetTeams().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .bragi.ValorantTeamCurrentMapState&gt; teams = 7 [json_name = "teams"];</code>
     */
    @java.lang.Override
    public /* nullable */
com.bragi.ValorantTeamCurrentMapState getTeamsOrDefault(
        java.lang.String key,
        /* nullable */
com.bragi.ValorantTeamCurrentMapState defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.bragi.ValorantTeamCurrentMapStateOrBuilder> map = internalGetMutableTeams().ensureBuilderMap();
      return map.containsKey(key) ? teamsConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .bragi.ValorantTeamCurrentMapState&gt; teams = 7 [json_name = "teams"];</code>
     */
    @java.lang.Override
    public com.bragi.ValorantTeamCurrentMapState getTeamsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.bragi.ValorantTeamCurrentMapStateOrBuilder> map = internalGetMutableTeams().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return teamsConverter.build(map.get(key));
    }
    public Builder clearTeams() {
      bitField0_ = (bitField0_ & ~0x00000040);
      internalGetMutableTeams().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .bragi.ValorantTeamCurrentMapState&gt; teams = 7 [json_name = "teams"];</code>
     */
    public Builder removeTeams(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableTeams().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.bragi.ValorantTeamCurrentMapState>
        getMutableTeams() {
      bitField0_ |= 0x00000040;
      return internalGetMutableTeams().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .bragi.ValorantTeamCurrentMapState&gt; teams = 7 [json_name = "teams"];</code>
     */
    public Builder putTeams(
        java.lang.String key,
        com.bragi.ValorantTeamCurrentMapState value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableTeams().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>map&lt;string, .bragi.ValorantTeamCurrentMapState&gt; teams = 7 [json_name = "teams"];</code>
     */
    public Builder putAllTeams(
        java.util.Map<java.lang.String, com.bragi.ValorantTeamCurrentMapState> values) {
      for (java.util.Map.Entry<java.lang.String, com.bragi.ValorantTeamCurrentMapState> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableTeams().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>map&lt;string, .bragi.ValorantTeamCurrentMapState&gt; teams = 7 [json_name = "teams"];</code>
     */
    public com.bragi.ValorantTeamCurrentMapState.Builder putTeamsBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.bragi.ValorantTeamCurrentMapStateOrBuilder> builderMap = internalGetMutableTeams().ensureBuilderMap();
      com.bragi.ValorantTeamCurrentMapStateOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.bragi.ValorantTeamCurrentMapState.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.bragi.ValorantTeamCurrentMapState) {
        entry = ((com.bragi.ValorantTeamCurrentMapState) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.bragi.ValorantTeamCurrentMapState.Builder) entry;
    }

    private com.bragi.ValorantPreviousRoundsState previousRounds_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.ValorantPreviousRoundsState, com.bragi.ValorantPreviousRoundsState.Builder, com.bragi.ValorantPreviousRoundsStateOrBuilder> previousRoundsBuilder_;
    /**
     * <code>.bragi.ValorantPreviousRoundsState previous_rounds = 8 [json_name = "previousRounds"];</code>
     * @return Whether the previousRounds field is set.
     */
    public boolean hasPreviousRounds() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.bragi.ValorantPreviousRoundsState previous_rounds = 8 [json_name = "previousRounds"];</code>
     * @return The previousRounds.
     */
    public com.bragi.ValorantPreviousRoundsState getPreviousRounds() {
      if (previousRoundsBuilder_ == null) {
        return previousRounds_ == null ? com.bragi.ValorantPreviousRoundsState.getDefaultInstance() : previousRounds_;
      } else {
        return previousRoundsBuilder_.getMessage();
      }
    }
    /**
     * <code>.bragi.ValorantPreviousRoundsState previous_rounds = 8 [json_name = "previousRounds"];</code>
     */
    public Builder setPreviousRounds(com.bragi.ValorantPreviousRoundsState value) {
      if (previousRoundsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        previousRounds_ = value;
      } else {
        previousRoundsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.ValorantPreviousRoundsState previous_rounds = 8 [json_name = "previousRounds"];</code>
     */
    public Builder setPreviousRounds(
        com.bragi.ValorantPreviousRoundsState.Builder builderForValue) {
      if (previousRoundsBuilder_ == null) {
        previousRounds_ = builderForValue.build();
      } else {
        previousRoundsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.ValorantPreviousRoundsState previous_rounds = 8 [json_name = "previousRounds"];</code>
     */
    public Builder mergePreviousRounds(com.bragi.ValorantPreviousRoundsState value) {
      if (previousRoundsBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          previousRounds_ != null &&
          previousRounds_ != com.bragi.ValorantPreviousRoundsState.getDefaultInstance()) {
          getPreviousRoundsBuilder().mergeFrom(value);
        } else {
          previousRounds_ = value;
        }
      } else {
        previousRoundsBuilder_.mergeFrom(value);
      }
      if (previousRounds_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.bragi.ValorantPreviousRoundsState previous_rounds = 8 [json_name = "previousRounds"];</code>
     */
    public Builder clearPreviousRounds() {
      bitField0_ = (bitField0_ & ~0x00000080);
      previousRounds_ = null;
      if (previousRoundsBuilder_ != null) {
        previousRoundsBuilder_.dispose();
        previousRoundsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.bragi.ValorantPreviousRoundsState previous_rounds = 8 [json_name = "previousRounds"];</code>
     */
    public com.bragi.ValorantPreviousRoundsState.Builder getPreviousRoundsBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getPreviousRoundsFieldBuilder().getBuilder();
    }
    /**
     * <code>.bragi.ValorantPreviousRoundsState previous_rounds = 8 [json_name = "previousRounds"];</code>
     */
    public com.bragi.ValorantPreviousRoundsStateOrBuilder getPreviousRoundsOrBuilder() {
      if (previousRoundsBuilder_ != null) {
        return previousRoundsBuilder_.getMessageOrBuilder();
      } else {
        return previousRounds_ == null ?
            com.bragi.ValorantPreviousRoundsState.getDefaultInstance() : previousRounds_;
      }
    }
    /**
     * <code>.bragi.ValorantPreviousRoundsState previous_rounds = 8 [json_name = "previousRounds"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bragi.ValorantPreviousRoundsState, com.bragi.ValorantPreviousRoundsState.Builder, com.bragi.ValorantPreviousRoundsStateOrBuilder> 
        getPreviousRoundsFieldBuilder() {
      if (previousRoundsBuilder_ == null) {
        previousRoundsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bragi.ValorantPreviousRoundsState, com.bragi.ValorantPreviousRoundsState.Builder, com.bragi.ValorantPreviousRoundsStateOrBuilder>(
                getPreviousRounds(),
                getParentForChildren(),
                isClean());
        previousRounds_ = null;
      }
      return previousRoundsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:bragi.ValorantCurrentMapState)
  }

  // @@protoc_insertion_point(class_scope:bragi.ValorantCurrentMapState)
  private static final com.bragi.ValorantCurrentMapState DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bragi.ValorantCurrentMapState();
  }

  public static com.bragi.ValorantCurrentMapState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValorantCurrentMapState>
      PARSER = new com.google.protobuf.AbstractParser<ValorantCurrentMapState>() {
    @java.lang.Override
    public ValorantCurrentMapState parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ValorantCurrentMapState> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ValorantCurrentMapState> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bragi.ValorantCurrentMapState getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

