// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bragi/valorant.proto
// Protobuf Java Version: 4.29.3

package com.bragi;

public interface ValorantPlayerCurrentRoundStatisticsStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bragi.ValorantPlayerCurrentRoundStatisticsState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string player_urn = 1 [json_name = "playerUrn"];</code>
   * @return The playerUrn.
   */
  java.lang.String getPlayerUrn();
  /**
   * <code>string player_urn = 1 [json_name = "playerUrn"];</code>
   * @return The bytes for playerUrn.
   */
  com.google.protobuf.ByteString
      getPlayerUrnBytes();

  /**
   * <code>bool is_alive = 2 [json_name = "isAlive"];</code>
   * @return The isAlive.
   */
  boolean getIsAlive();
}
