// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.1-0.20241121165744-79df5c4772f2
// source: bragi/rush_madden.proto

package bragi

import (
	durationpb1 "github.com/planetscale/vtprotobuf/types/known/durationpb"
	timestamppb1 "github.com/planetscale/vtprotobuf/types/known/timestamppb"
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *RushMaddenMatchMessage_Payload) CloneVT() *RushMaddenMatchMessage_Payload {
	if m == nil {
		return (*RushMaddenMatchMessage_Payload)(nil)
	}
	r := new(RushMaddenMatchMessage_Payload)
	if m.Payload != nil {
		r.Payload = m.Payload.(interface {
			CloneVT() isRushMaddenMatchMessage_Payload_Payload
		}).CloneVT()
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenMatchMessage_Payload) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenMatchMessage_Payload_Snapshot) CloneVT() isRushMaddenMatchMessage_Payload_Payload {
	if m == nil {
		return (*RushMaddenMatchMessage_Payload_Snapshot)(nil)
	}
	r := new(RushMaddenMatchMessage_Payload_Snapshot)
	r.Snapshot = m.Snapshot.CloneVT()
	return r
}

func (m *RushMaddenMatchMessage_Payload_Update) CloneVT() isRushMaddenMatchMessage_Payload_Payload {
	if m == nil {
		return (*RushMaddenMatchMessage_Payload_Update)(nil)
	}
	r := new(RushMaddenMatchMessage_Payload_Update)
	r.Update = m.Update.CloneVT()
	return r
}

func (m *RushMaddenMatchMessage) CloneVT() *RushMaddenMatchMessage {
	if m == nil {
		return (*RushMaddenMatchMessage)(nil)
	}
	r := new(RushMaddenMatchMessage)
	r.MatchUrn = m.MatchUrn
	r.Sequence = m.Sequence
	r.Timestamp = (*timestamppb.Timestamp)((*timestamppb1.Timestamp)(m.Timestamp).CloneVT())
	r.DataStatus = m.DataStatus
	r.Payload = m.Payload.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenMatchMessage) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenMatchSnapshot) CloneVT() *RushMaddenMatchSnapshot {
	if m == nil {
		return (*RushMaddenMatchSnapshot)(nil)
	}
	r := new(RushMaddenMatchSnapshot)
	r.MatchUrn = m.MatchUrn
	r.Sequence = m.Sequence
	r.Timestamp = (*timestamppb.Timestamp)((*timestamppb1.Timestamp)(m.Timestamp).CloneVT())
	r.DataStatus = m.DataStatus
	r.MatchState = m.MatchState.CloneVT()
	r.Tournament = m.Tournament.CloneVT()
	if rhs := m.Announcements; rhs != nil {
		tmpContainer := make([]*Announcement, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Announcements = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenMatchSnapshot) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenMatchUpdate_Payload) CloneVT() *RushMaddenMatchUpdate_Payload {
	if m == nil {
		return (*RushMaddenMatchUpdate_Payload)(nil)
	}
	r := new(RushMaddenMatchUpdate_Payload)
	if m.Payload != nil {
		r.Payload = m.Payload.(interface {
			CloneVT() isRushMaddenMatchUpdate_Payload_Payload
		}).CloneVT()
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenMatchUpdate_Payload) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenMatchUpdate_Payload_MatchState) CloneVT() isRushMaddenMatchUpdate_Payload_Payload {
	if m == nil {
		return (*RushMaddenMatchUpdate_Payload_MatchState)(nil)
	}
	r := new(RushMaddenMatchUpdate_Payload_MatchState)
	r.MatchState = m.MatchState.CloneVT()
	return r
}

func (m *RushMaddenMatchUpdate_Payload_PartialUpdates) CloneVT() isRushMaddenMatchUpdate_Payload_Payload {
	if m == nil {
		return (*RushMaddenMatchUpdate_Payload_PartialUpdates)(nil)
	}
	r := new(RushMaddenMatchUpdate_Payload_PartialUpdates)
	r.PartialUpdates = m.PartialUpdates.CloneVT()
	return r
}

func (m *RushMaddenMatchUpdate) CloneVT() *RushMaddenMatchUpdate {
	if m == nil {
		return (*RushMaddenMatchUpdate)(nil)
	}
	r := new(RushMaddenMatchUpdate)
	r.Payload = m.Payload.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenMatchUpdate) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenMatchStatePartialUpdates) CloneVT() *RushMaddenMatchStatePartialUpdates {
	if m == nil {
		return (*RushMaddenMatchStatePartialUpdates)(nil)
	}
	r := new(RushMaddenMatchStatePartialUpdates)
	if rhs := m.Updates; rhs != nil {
		tmpContainer := make([]*RushMaddenMatchStatePartialUpdate, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Updates = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenMatchStatePartialUpdates) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenMatchStatePartialUpdate) CloneVT() *RushMaddenMatchStatePartialUpdate {
	if m == nil {
		return (*RushMaddenMatchStatePartialUpdate)(nil)
	}
	r := new(RushMaddenMatchStatePartialUpdate)
	if m.Update != nil {
		r.Update = m.Update.(interface {
			CloneVT() isRushMaddenMatchStatePartialUpdate_Update
		}).CloneVT()
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenMatchStatePartialUpdate) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenMatchStatePartialUpdate_CurrentGameState) CloneVT() isRushMaddenMatchStatePartialUpdate_Update {
	if m == nil {
		return (*RushMaddenMatchStatePartialUpdate_CurrentGameState)(nil)
	}
	r := new(RushMaddenMatchStatePartialUpdate_CurrentGameState)
	r.CurrentGameState = m.CurrentGameState.CloneVT()
	return r
}

func (m *RushMaddenMatchStatePartialUpdate_CurrentGameStatePartialUpdate) CloneVT() isRushMaddenMatchStatePartialUpdate_Update {
	if m == nil {
		return (*RushMaddenMatchStatePartialUpdate_CurrentGameStatePartialUpdate)(nil)
	}
	r := new(RushMaddenMatchStatePartialUpdate_CurrentGameStatePartialUpdate)
	r.CurrentGameStatePartialUpdate = m.CurrentGameStatePartialUpdate.CloneVT()
	return r
}

func (m *RushMaddenMatchStatePartialUpdate_Timeline) CloneVT() isRushMaddenMatchStatePartialUpdate_Update {
	if m == nil {
		return (*RushMaddenMatchStatePartialUpdate_Timeline)(nil)
	}
	r := new(RushMaddenMatchStatePartialUpdate_Timeline)
	r.Timeline = m.Timeline.CloneVT()
	return r
}

func (m *RushMaddenMatchState) CloneVT() *RushMaddenMatchState {
	if m == nil {
		return (*RushMaddenMatchState)(nil)
	}
	r := new(RushMaddenMatchState)
	r.MatchUrn = m.MatchUrn
	r.MatchType = m.MatchType
	r.HomeTeam = m.HomeTeam.CloneVT()
	r.AwayTeam = m.AwayTeam.CloneVT()
	r.MatchStatus = m.MatchStatus
	r.Timeline = m.Timeline.CloneVT()
	r.CurrentGame = m.CurrentGame.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenMatchState) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenCurrentGameStatePartialUpdate) CloneVT() *RushMaddenCurrentGameStatePartialUpdate {
	if m == nil {
		return (*RushMaddenCurrentGameStatePartialUpdate)(nil)
	}
	r := new(RushMaddenCurrentGameStatePartialUpdate)
	if m.Update != nil {
		r.Update = m.Update.(interface {
			CloneVT() isRushMaddenCurrentGameStatePartialUpdate_Update
		}).CloneVT()
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenCurrentGameStatePartialUpdate) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenCurrentGameStatePartialUpdate_GameTime) CloneVT() isRushMaddenCurrentGameStatePartialUpdate_Update {
	if m == nil {
		return (*RushMaddenCurrentGameStatePartialUpdate_GameTime)(nil)
	}
	r := new(RushMaddenCurrentGameStatePartialUpdate_GameTime)
	r.GameTime = m.GameTime.CloneVT()
	return r
}

func (m *RushMaddenCurrentGameStatePartialUpdate_Score) CloneVT() isRushMaddenCurrentGameStatePartialUpdate_Update {
	if m == nil {
		return (*RushMaddenCurrentGameStatePartialUpdate_Score)(nil)
	}
	r := new(RushMaddenCurrentGameStatePartialUpdate_Score)
	r.Score = m.Score.CloneVT()
	return r
}

func (m *RushMaddenCurrentGameStatePartialUpdate_TeamCurrentGameState) CloneVT() isRushMaddenCurrentGameStatePartialUpdate_Update {
	if m == nil {
		return (*RushMaddenCurrentGameStatePartialUpdate_TeamCurrentGameState)(nil)
	}
	r := new(RushMaddenCurrentGameStatePartialUpdate_TeamCurrentGameState)
	r.TeamCurrentGameState = m.TeamCurrentGameState.CloneVT()
	return r
}

func (m *RushMaddenCurrentGameStatePartialUpdate_TeamCurrentGamePartialUpdate) CloneVT() isRushMaddenCurrentGameStatePartialUpdate_Update {
	if m == nil {
		return (*RushMaddenCurrentGameStatePartialUpdate_TeamCurrentGamePartialUpdate)(nil)
	}
	r := new(RushMaddenCurrentGameStatePartialUpdate_TeamCurrentGamePartialUpdate)
	r.TeamCurrentGamePartialUpdate = m.TeamCurrentGamePartialUpdate.CloneVT()
	return r
}

func (m *RushMaddenCurrentGameStatePartialUpdate_PossessionSide) CloneVT() isRushMaddenCurrentGameStatePartialUpdate_Update {
	if m == nil {
		return (*RushMaddenCurrentGameStatePartialUpdate_PossessionSide)(nil)
	}
	r := new(RushMaddenCurrentGameStatePartialUpdate_PossessionSide)
	r.PossessionSide = m.PossessionSide
	return r
}

func (m *RushMaddenCurrentGameStatePartialUpdate_Down) CloneVT() isRushMaddenCurrentGameStatePartialUpdate_Update {
	if m == nil {
		return (*RushMaddenCurrentGameStatePartialUpdate_Down)(nil)
	}
	r := new(RushMaddenCurrentGameStatePartialUpdate_Down)
	r.Down = m.Down
	return r
}

func (m *RushMaddenCurrentGameStatePartialUpdate_FirstDownDistance) CloneVT() isRushMaddenCurrentGameStatePartialUpdate_Update {
	if m == nil {
		return (*RushMaddenCurrentGameStatePartialUpdate_FirstDownDistance)(nil)
	}
	r := new(RushMaddenCurrentGameStatePartialUpdate_FirstDownDistance)
	r.FirstDownDistance = m.FirstDownDistance.CloneVT()
	return r
}

func (m *RushMaddenCurrentGameStatePartialUpdate_YardsToEndzone) CloneVT() isRushMaddenCurrentGameStatePartialUpdate_Update {
	if m == nil {
		return (*RushMaddenCurrentGameStatePartialUpdate_YardsToEndzone)(nil)
	}
	r := new(RushMaddenCurrentGameStatePartialUpdate_YardsToEndzone)
	r.YardsToEndzone = m.YardsToEndzone
	return r
}

func (m *RushMaddenCurrentGameStatePartialUpdate_Quarter) CloneVT() isRushMaddenCurrentGameStatePartialUpdate_Update {
	if m == nil {
		return (*RushMaddenCurrentGameStatePartialUpdate_Quarter)(nil)
	}
	r := new(RushMaddenCurrentGameStatePartialUpdate_Quarter)
	r.Quarter = m.Quarter
	return r
}

func (m *RushMaddenCurrentGameState) CloneVT() *RushMaddenCurrentGameState {
	if m == nil {
		return (*RushMaddenCurrentGameState)(nil)
	}
	r := new(RushMaddenCurrentGameState)
	r.Quarter = m.Quarter
	r.GameTime = m.GameTime.CloneVT()
	r.Score = m.Score.CloneVT()
	r.GamePaused = m.GamePaused
	r.PossessionSide = m.PossessionSide
	r.Down = m.Down
	r.FirstDownDistance = m.FirstDownDistance.CloneVT()
	r.YardsToEndzone = m.YardsToEndzone
	if rhs := m.Teams; rhs != nil {
		tmpContainer := make(map[string]*RushMaddenTeamCurrentGameState, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Teams = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenCurrentGameState) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenCurrentGameTimeState) CloneVT() *RushMaddenCurrentGameTimeState {
	if m == nil {
		return (*RushMaddenCurrentGameTimeState)(nil)
	}
	r := new(RushMaddenCurrentGameTimeState)
	r.RemainingTime = (*durationpb.Duration)((*durationpb1.Duration)(m.RemainingTime).CloneVT())
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenCurrentGameTimeState) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenCurrentGameScoreState) CloneVT() *RushMaddenCurrentGameScoreState {
	if m == nil {
		return (*RushMaddenCurrentGameScoreState)(nil)
	}
	r := new(RushMaddenCurrentGameScoreState)
	r.HomeScore = m.HomeScore
	r.AwayScore = m.AwayScore
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenCurrentGameScoreState) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenFirstDownDistance) CloneVT() *RushMaddenFirstDownDistance {
	if m == nil {
		return (*RushMaddenFirstDownDistance)(nil)
	}
	r := new(RushMaddenFirstDownDistance)
	if m.Value != nil {
		r.Value = m.Value.(interface {
			CloneVT() isRushMaddenFirstDownDistance_Value
		}).CloneVT()
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenFirstDownDistance) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenFirstDownDistance_Yards) CloneVT() isRushMaddenFirstDownDistance_Value {
	if m == nil {
		return (*RushMaddenFirstDownDistance_Yards)(nil)
	}
	r := new(RushMaddenFirstDownDistance_Yards)
	r.Yards = m.Yards
	return r
}

func (m *RushMaddenFirstDownDistance_Type) CloneVT() isRushMaddenFirstDownDistance_Value {
	if m == nil {
		return (*RushMaddenFirstDownDistance_Type)(nil)
	}
	r := new(RushMaddenFirstDownDistance_Type)
	r.Type = m.Type
	return r
}

func (m *RushMaddenTeamCurrentGameStatePartialUpdate_Payload) CloneVT() *RushMaddenTeamCurrentGameStatePartialUpdate_Payload {
	if m == nil {
		return (*RushMaddenTeamCurrentGameStatePartialUpdate_Payload)(nil)
	}
	r := new(RushMaddenTeamCurrentGameStatePartialUpdate_Payload)
	if m.Payload != nil {
		r.Payload = m.Payload.(interface {
			CloneVT() isRushMaddenTeamCurrentGameStatePartialUpdate_Payload_Payload
		}).CloneVT()
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenTeamCurrentGameStatePartialUpdate_Payload) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenTeamCurrentGameStatePartialUpdate_Payload_GameStatistics) CloneVT() isRushMaddenTeamCurrentGameStatePartialUpdate_Payload_Payload {
	if m == nil {
		return (*RushMaddenTeamCurrentGameStatePartialUpdate_Payload_GameStatistics)(nil)
	}
	r := new(RushMaddenTeamCurrentGameStatePartialUpdate_Payload_GameStatistics)
	r.GameStatistics = m.GameStatistics.CloneVT()
	return r
}

func (m *RushMaddenTeamCurrentGameStatePartialUpdate_Payload_Player) CloneVT() isRushMaddenTeamCurrentGameStatePartialUpdate_Payload_Payload {
	if m == nil {
		return (*RushMaddenTeamCurrentGameStatePartialUpdate_Payload_Player)(nil)
	}
	r := new(RushMaddenTeamCurrentGameStatePartialUpdate_Payload_Player)
	r.Player = m.Player.CloneVT()
	return r
}

func (m *RushMaddenTeamCurrentGameStatePartialUpdate) CloneVT() *RushMaddenTeamCurrentGameStatePartialUpdate {
	if m == nil {
		return (*RushMaddenTeamCurrentGameStatePartialUpdate)(nil)
	}
	r := new(RushMaddenTeamCurrentGameStatePartialUpdate)
	r.TeamUrn = m.TeamUrn
	r.Payload = m.Payload.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenTeamCurrentGameStatePartialUpdate) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenTeamCurrentGameState) CloneVT() *RushMaddenTeamCurrentGameState {
	if m == nil {
		return (*RushMaddenTeamCurrentGameState)(nil)
	}
	r := new(RushMaddenTeamCurrentGameState)
	r.TeamUrn = m.TeamUrn
	r.GameStatistics = m.GameStatistics.CloneVT()
	r.Player = m.Player.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenTeamCurrentGameState) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenPlayerCurrentGameState) CloneVT() *RushMaddenPlayerCurrentGameState {
	if m == nil {
		return (*RushMaddenPlayerCurrentGameState)(nil)
	}
	r := new(RushMaddenPlayerCurrentGameState)
	r.PlayerUrn = m.PlayerUrn
	r.ExtName = m.ExtName
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenPlayerCurrentGameState) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenTeamCurrentGameStatisticsState) CloneVT() *RushMaddenTeamCurrentGameStatisticsState {
	if m == nil {
		return (*RushMaddenTeamCurrentGameStatisticsState)(nil)
	}
	r := new(RushMaddenTeamCurrentGameStatisticsState)
	r.Score = m.Score
	r.TimeoutsLeft = m.TimeoutsLeft
	if rhs := m.QuarterPoints; rhs != nil {
		tmpContainer := make([]*RushMaddenQuarterPoints, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.QuarterPoints = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenTeamCurrentGameStatisticsState) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenQuarterPoints) CloneVT() *RushMaddenQuarterPoints {
	if m == nil {
		return (*RushMaddenQuarterPoints)(nil)
	}
	r := new(RushMaddenQuarterPoints)
	r.Quarter = m.Quarter
	r.Points = m.Points
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenQuarterPoints) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenTimelineState) CloneVT() *RushMaddenTimelineState {
	if m == nil {
		return (*RushMaddenTimelineState)(nil)
	}
	r := new(RushMaddenTimelineState)
	if rhs := m.Events; rhs != nil {
		tmpContainer := make([]*RushMaddenTimelineEvent, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Events = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenTimelineState) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *RushMaddenTimelineEvent) CloneVT() *RushMaddenTimelineEvent {
	if m == nil {
		return (*RushMaddenTimelineEvent)(nil)
	}
	r := new(RushMaddenTimelineEvent)
	r.TeamUrn = m.TeamUrn
	r.EventType = m.EventType
	r.RemainingTime = (*durationpb.Duration)((*durationpb1.Duration)(m.RemainingTime).CloneVT())
	r.Quarter = m.Quarter
	r.Down = m.Down
	r.FirstDownDistance = m.FirstDownDistance.CloneVT()
	r.YardsToEndzone = m.YardsToEndzone
	r.PossessionSide = m.PossessionSide
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *RushMaddenTimelineEvent) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (this *RushMaddenMatchMessage_Payload) EqualVT(that *RushMaddenMatchMessage_Payload) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Payload == nil && that.Payload != nil {
		return false
	} else if this.Payload != nil {
		if that.Payload == nil {
			return false
		}
		if !this.Payload.(interface {
			EqualVT(isRushMaddenMatchMessage_Payload_Payload) bool
		}).EqualVT(that.Payload) {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenMatchMessage_Payload) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenMatchMessage_Payload)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenMatchMessage_Payload_Snapshot) EqualVT(thatIface isRushMaddenMatchMessage_Payload_Payload) bool {
	that, ok := thatIface.(*RushMaddenMatchMessage_Payload_Snapshot)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if p, q := this.Snapshot, that.Snapshot; p != q {
		if p == nil {
			p = &RushMaddenMatchSnapshot{}
		}
		if q == nil {
			q = &RushMaddenMatchSnapshot{}
		}
		if !p.EqualVT(q) {
			return false
		}
	}
	return true
}

func (this *RushMaddenMatchMessage_Payload_Update) EqualVT(thatIface isRushMaddenMatchMessage_Payload_Payload) bool {
	that, ok := thatIface.(*RushMaddenMatchMessage_Payload_Update)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if p, q := this.Update, that.Update; p != q {
		if p == nil {
			p = &RushMaddenMatchUpdate{}
		}
		if q == nil {
			q = &RushMaddenMatchUpdate{}
		}
		if !p.EqualVT(q) {
			return false
		}
	}
	return true
}

func (this *RushMaddenMatchMessage) EqualVT(that *RushMaddenMatchMessage) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.MatchUrn != that.MatchUrn {
		return false
	}
	if this.Sequence != that.Sequence {
		return false
	}
	if !(*timestamppb1.Timestamp)(this.Timestamp).EqualVT((*timestamppb1.Timestamp)(that.Timestamp)) {
		return false
	}
	if this.DataStatus != that.DataStatus {
		return false
	}
	if !this.Payload.EqualVT(that.Payload) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenMatchMessage) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenMatchMessage)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenMatchSnapshot) EqualVT(that *RushMaddenMatchSnapshot) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.MatchUrn != that.MatchUrn {
		return false
	}
	if this.Sequence != that.Sequence {
		return false
	}
	if !(*timestamppb1.Timestamp)(this.Timestamp).EqualVT((*timestamppb1.Timestamp)(that.Timestamp)) {
		return false
	}
	if this.DataStatus != that.DataStatus {
		return false
	}
	if len(this.Announcements) != len(that.Announcements) {
		return false
	}
	for i, vx := range this.Announcements {
		vy := that.Announcements[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Announcement{}
			}
			if q == nil {
				q = &Announcement{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if !this.MatchState.EqualVT(that.MatchState) {
		return false
	}
	if !this.Tournament.EqualVT(that.Tournament) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenMatchSnapshot) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenMatchSnapshot)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenMatchUpdate_Payload) EqualVT(that *RushMaddenMatchUpdate_Payload) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Payload == nil && that.Payload != nil {
		return false
	} else if this.Payload != nil {
		if that.Payload == nil {
			return false
		}
		if !this.Payload.(interface {
			EqualVT(isRushMaddenMatchUpdate_Payload_Payload) bool
		}).EqualVT(that.Payload) {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenMatchUpdate_Payload) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenMatchUpdate_Payload)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenMatchUpdate_Payload_MatchState) EqualVT(thatIface isRushMaddenMatchUpdate_Payload_Payload) bool {
	that, ok := thatIface.(*RushMaddenMatchUpdate_Payload_MatchState)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if p, q := this.MatchState, that.MatchState; p != q {
		if p == nil {
			p = &RushMaddenMatchState{}
		}
		if q == nil {
			q = &RushMaddenMatchState{}
		}
		if !p.EqualVT(q) {
			return false
		}
	}
	return true
}

func (this *RushMaddenMatchUpdate_Payload_PartialUpdates) EqualVT(thatIface isRushMaddenMatchUpdate_Payload_Payload) bool {
	that, ok := thatIface.(*RushMaddenMatchUpdate_Payload_PartialUpdates)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if p, q := this.PartialUpdates, that.PartialUpdates; p != q {
		if p == nil {
			p = &RushMaddenMatchStatePartialUpdates{}
		}
		if q == nil {
			q = &RushMaddenMatchStatePartialUpdates{}
		}
		if !p.EqualVT(q) {
			return false
		}
	}
	return true
}

func (this *RushMaddenMatchUpdate) EqualVT(that *RushMaddenMatchUpdate) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !this.Payload.EqualVT(that.Payload) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenMatchUpdate) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenMatchUpdate)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenMatchStatePartialUpdates) EqualVT(that *RushMaddenMatchStatePartialUpdates) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Updates) != len(that.Updates) {
		return false
	}
	for i, vx := range this.Updates {
		vy := that.Updates[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &RushMaddenMatchStatePartialUpdate{}
			}
			if q == nil {
				q = &RushMaddenMatchStatePartialUpdate{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenMatchStatePartialUpdates) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenMatchStatePartialUpdates)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenMatchStatePartialUpdate) EqualVT(that *RushMaddenMatchStatePartialUpdate) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Update == nil && that.Update != nil {
		return false
	} else if this.Update != nil {
		if that.Update == nil {
			return false
		}
		if !this.Update.(interface {
			EqualVT(isRushMaddenMatchStatePartialUpdate_Update) bool
		}).EqualVT(that.Update) {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenMatchStatePartialUpdate) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenMatchStatePartialUpdate)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenMatchStatePartialUpdate_CurrentGameState) EqualVT(thatIface isRushMaddenMatchStatePartialUpdate_Update) bool {
	that, ok := thatIface.(*RushMaddenMatchStatePartialUpdate_CurrentGameState)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if p, q := this.CurrentGameState, that.CurrentGameState; p != q {
		if p == nil {
			p = &RushMaddenCurrentGameState{}
		}
		if q == nil {
			q = &RushMaddenCurrentGameState{}
		}
		if !p.EqualVT(q) {
			return false
		}
	}
	return true
}

func (this *RushMaddenMatchStatePartialUpdate_CurrentGameStatePartialUpdate) EqualVT(thatIface isRushMaddenMatchStatePartialUpdate_Update) bool {
	that, ok := thatIface.(*RushMaddenMatchStatePartialUpdate_CurrentGameStatePartialUpdate)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if p, q := this.CurrentGameStatePartialUpdate, that.CurrentGameStatePartialUpdate; p != q {
		if p == nil {
			p = &RushMaddenCurrentGameStatePartialUpdate{}
		}
		if q == nil {
			q = &RushMaddenCurrentGameStatePartialUpdate{}
		}
		if !p.EqualVT(q) {
			return false
		}
	}
	return true
}

func (this *RushMaddenMatchStatePartialUpdate_Timeline) EqualVT(thatIface isRushMaddenMatchStatePartialUpdate_Update) bool {
	that, ok := thatIface.(*RushMaddenMatchStatePartialUpdate_Timeline)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if p, q := this.Timeline, that.Timeline; p != q {
		if p == nil {
			p = &RushMaddenTimelineState{}
		}
		if q == nil {
			q = &RushMaddenTimelineState{}
		}
		if !p.EqualVT(q) {
			return false
		}
	}
	return true
}

func (this *RushMaddenMatchState) EqualVT(that *RushMaddenMatchState) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.MatchUrn != that.MatchUrn {
		return false
	}
	if this.MatchType != that.MatchType {
		return false
	}
	if !this.HomeTeam.EqualVT(that.HomeTeam) {
		return false
	}
	if !this.AwayTeam.EqualVT(that.AwayTeam) {
		return false
	}
	if this.MatchStatus != that.MatchStatus {
		return false
	}
	if !this.Timeline.EqualVT(that.Timeline) {
		return false
	}
	if !this.CurrentGame.EqualVT(that.CurrentGame) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenMatchState) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenMatchState)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenCurrentGameStatePartialUpdate) EqualVT(that *RushMaddenCurrentGameStatePartialUpdate) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Update == nil && that.Update != nil {
		return false
	} else if this.Update != nil {
		if that.Update == nil {
			return false
		}
		if !this.Update.(interface {
			EqualVT(isRushMaddenCurrentGameStatePartialUpdate_Update) bool
		}).EqualVT(that.Update) {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenCurrentGameStatePartialUpdate) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenCurrentGameStatePartialUpdate)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenCurrentGameStatePartialUpdate_GameTime) EqualVT(thatIface isRushMaddenCurrentGameStatePartialUpdate_Update) bool {
	that, ok := thatIface.(*RushMaddenCurrentGameStatePartialUpdate_GameTime)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if p, q := this.GameTime, that.GameTime; p != q {
		if p == nil {
			p = &RushMaddenCurrentGameTimeState{}
		}
		if q == nil {
			q = &RushMaddenCurrentGameTimeState{}
		}
		if !p.EqualVT(q) {
			return false
		}
	}
	return true
}

func (this *RushMaddenCurrentGameStatePartialUpdate_Score) EqualVT(thatIface isRushMaddenCurrentGameStatePartialUpdate_Update) bool {
	that, ok := thatIface.(*RushMaddenCurrentGameStatePartialUpdate_Score)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if p, q := this.Score, that.Score; p != q {
		if p == nil {
			p = &RushMaddenCurrentGameScoreState{}
		}
		if q == nil {
			q = &RushMaddenCurrentGameScoreState{}
		}
		if !p.EqualVT(q) {
			return false
		}
	}
	return true
}

func (this *RushMaddenCurrentGameStatePartialUpdate_TeamCurrentGameState) EqualVT(thatIface isRushMaddenCurrentGameStatePartialUpdate_Update) bool {
	that, ok := thatIface.(*RushMaddenCurrentGameStatePartialUpdate_TeamCurrentGameState)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if p, q := this.TeamCurrentGameState, that.TeamCurrentGameState; p != q {
		if p == nil {
			p = &RushMaddenTeamCurrentGameState{}
		}
		if q == nil {
			q = &RushMaddenTeamCurrentGameState{}
		}
		if !p.EqualVT(q) {
			return false
		}
	}
	return true
}

func (this *RushMaddenCurrentGameStatePartialUpdate_TeamCurrentGamePartialUpdate) EqualVT(thatIface isRushMaddenCurrentGameStatePartialUpdate_Update) bool {
	that, ok := thatIface.(*RushMaddenCurrentGameStatePartialUpdate_TeamCurrentGamePartialUpdate)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if p, q := this.TeamCurrentGamePartialUpdate, that.TeamCurrentGamePartialUpdate; p != q {
		if p == nil {
			p = &RushMaddenTeamCurrentGameStatePartialUpdate{}
		}
		if q == nil {
			q = &RushMaddenTeamCurrentGameStatePartialUpdate{}
		}
		if !p.EqualVT(q) {
			return false
		}
	}
	return true
}

func (this *RushMaddenCurrentGameStatePartialUpdate_PossessionSide) EqualVT(thatIface isRushMaddenCurrentGameStatePartialUpdate_Update) bool {
	that, ok := thatIface.(*RushMaddenCurrentGameStatePartialUpdate_PossessionSide)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if this.PossessionSide != that.PossessionSide {
		return false
	}
	return true
}

func (this *RushMaddenCurrentGameStatePartialUpdate_Down) EqualVT(thatIface isRushMaddenCurrentGameStatePartialUpdate_Update) bool {
	that, ok := thatIface.(*RushMaddenCurrentGameStatePartialUpdate_Down)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if this.Down != that.Down {
		return false
	}
	return true
}

func (this *RushMaddenCurrentGameStatePartialUpdate_FirstDownDistance) EqualVT(thatIface isRushMaddenCurrentGameStatePartialUpdate_Update) bool {
	that, ok := thatIface.(*RushMaddenCurrentGameStatePartialUpdate_FirstDownDistance)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if p, q := this.FirstDownDistance, that.FirstDownDistance; p != q {
		if p == nil {
			p = &RushMaddenFirstDownDistance{}
		}
		if q == nil {
			q = &RushMaddenFirstDownDistance{}
		}
		if !p.EqualVT(q) {
			return false
		}
	}
	return true
}

func (this *RushMaddenCurrentGameStatePartialUpdate_YardsToEndzone) EqualVT(thatIface isRushMaddenCurrentGameStatePartialUpdate_Update) bool {
	that, ok := thatIface.(*RushMaddenCurrentGameStatePartialUpdate_YardsToEndzone)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if this.YardsToEndzone != that.YardsToEndzone {
		return false
	}
	return true
}

func (this *RushMaddenCurrentGameStatePartialUpdate_Quarter) EqualVT(thatIface isRushMaddenCurrentGameStatePartialUpdate_Update) bool {
	that, ok := thatIface.(*RushMaddenCurrentGameStatePartialUpdate_Quarter)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if this.Quarter != that.Quarter {
		return false
	}
	return true
}

func (this *RushMaddenCurrentGameState) EqualVT(that *RushMaddenCurrentGameState) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Quarter != that.Quarter {
		return false
	}
	if !this.GameTime.EqualVT(that.GameTime) {
		return false
	}
	if !this.Score.EqualVT(that.Score) {
		return false
	}
	if this.GamePaused != that.GamePaused {
		return false
	}
	if len(this.Teams) != len(that.Teams) {
		return false
	}
	for i, vx := range this.Teams {
		vy, ok := that.Teams[i]
		if !ok {
			return false
		}
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &RushMaddenTeamCurrentGameState{}
			}
			if q == nil {
				q = &RushMaddenTeamCurrentGameState{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if this.PossessionSide != that.PossessionSide {
		return false
	}
	if this.Down != that.Down {
		return false
	}
	if !this.FirstDownDistance.EqualVT(that.FirstDownDistance) {
		return false
	}
	if this.YardsToEndzone != that.YardsToEndzone {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenCurrentGameState) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenCurrentGameState)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenCurrentGameTimeState) EqualVT(that *RushMaddenCurrentGameTimeState) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !(*durationpb1.Duration)(this.RemainingTime).EqualVT((*durationpb1.Duration)(that.RemainingTime)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenCurrentGameTimeState) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenCurrentGameTimeState)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenCurrentGameScoreState) EqualVT(that *RushMaddenCurrentGameScoreState) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.HomeScore != that.HomeScore {
		return false
	}
	if this.AwayScore != that.AwayScore {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenCurrentGameScoreState) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenCurrentGameScoreState)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenFirstDownDistance) EqualVT(that *RushMaddenFirstDownDistance) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Value == nil && that.Value != nil {
		return false
	} else if this.Value != nil {
		if that.Value == nil {
			return false
		}
		if !this.Value.(interface {
			EqualVT(isRushMaddenFirstDownDistance_Value) bool
		}).EqualVT(that.Value) {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenFirstDownDistance) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenFirstDownDistance)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenFirstDownDistance_Yards) EqualVT(thatIface isRushMaddenFirstDownDistance_Value) bool {
	that, ok := thatIface.(*RushMaddenFirstDownDistance_Yards)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if this.Yards != that.Yards {
		return false
	}
	return true
}

func (this *RushMaddenFirstDownDistance_Type) EqualVT(thatIface isRushMaddenFirstDownDistance_Value) bool {
	that, ok := thatIface.(*RushMaddenFirstDownDistance_Type)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if this.Type != that.Type {
		return false
	}
	return true
}

func (this *RushMaddenTeamCurrentGameStatePartialUpdate_Payload) EqualVT(that *RushMaddenTeamCurrentGameStatePartialUpdate_Payload) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Payload == nil && that.Payload != nil {
		return false
	} else if this.Payload != nil {
		if that.Payload == nil {
			return false
		}
		if !this.Payload.(interface {
			EqualVT(isRushMaddenTeamCurrentGameStatePartialUpdate_Payload_Payload) bool
		}).EqualVT(that.Payload) {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenTeamCurrentGameStatePartialUpdate_Payload) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenTeamCurrentGameStatePartialUpdate_Payload)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenTeamCurrentGameStatePartialUpdate_Payload_GameStatistics) EqualVT(thatIface isRushMaddenTeamCurrentGameStatePartialUpdate_Payload_Payload) bool {
	that, ok := thatIface.(*RushMaddenTeamCurrentGameStatePartialUpdate_Payload_GameStatistics)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if p, q := this.GameStatistics, that.GameStatistics; p != q {
		if p == nil {
			p = &RushMaddenTeamCurrentGameStatisticsState{}
		}
		if q == nil {
			q = &RushMaddenTeamCurrentGameStatisticsState{}
		}
		if !p.EqualVT(q) {
			return false
		}
	}
	return true
}

func (this *RushMaddenTeamCurrentGameStatePartialUpdate_Payload_Player) EqualVT(thatIface isRushMaddenTeamCurrentGameStatePartialUpdate_Payload_Payload) bool {
	that, ok := thatIface.(*RushMaddenTeamCurrentGameStatePartialUpdate_Payload_Player)
	if !ok {
		return false
	}
	if this == that {
		return true
	}
	if this == nil && that != nil || this != nil && that == nil {
		return false
	}
	if p, q := this.Player, that.Player; p != q {
		if p == nil {
			p = &RushMaddenPlayerCurrentGameState{}
		}
		if q == nil {
			q = &RushMaddenPlayerCurrentGameState{}
		}
		if !p.EqualVT(q) {
			return false
		}
	}
	return true
}

func (this *RushMaddenTeamCurrentGameStatePartialUpdate) EqualVT(that *RushMaddenTeamCurrentGameStatePartialUpdate) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.TeamUrn != that.TeamUrn {
		return false
	}
	if !this.Payload.EqualVT(that.Payload) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenTeamCurrentGameStatePartialUpdate) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenTeamCurrentGameStatePartialUpdate)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenTeamCurrentGameState) EqualVT(that *RushMaddenTeamCurrentGameState) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.TeamUrn != that.TeamUrn {
		return false
	}
	if !this.GameStatistics.EqualVT(that.GameStatistics) {
		return false
	}
	if !this.Player.EqualVT(that.Player) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenTeamCurrentGameState) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenTeamCurrentGameState)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenPlayerCurrentGameState) EqualVT(that *RushMaddenPlayerCurrentGameState) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.PlayerUrn != that.PlayerUrn {
		return false
	}
	if this.ExtName != that.ExtName {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenPlayerCurrentGameState) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenPlayerCurrentGameState)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenTeamCurrentGameStatisticsState) EqualVT(that *RushMaddenTeamCurrentGameStatisticsState) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Score != that.Score {
		return false
	}
	if len(this.QuarterPoints) != len(that.QuarterPoints) {
		return false
	}
	for i, vx := range this.QuarterPoints {
		vy := that.QuarterPoints[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &RushMaddenQuarterPoints{}
			}
			if q == nil {
				q = &RushMaddenQuarterPoints{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if this.TimeoutsLeft != that.TimeoutsLeft {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenTeamCurrentGameStatisticsState) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenTeamCurrentGameStatisticsState)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenQuarterPoints) EqualVT(that *RushMaddenQuarterPoints) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Quarter != that.Quarter {
		return false
	}
	if this.Points != that.Points {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenQuarterPoints) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenQuarterPoints)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenTimelineState) EqualVT(that *RushMaddenTimelineState) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Events) != len(that.Events) {
		return false
	}
	for i, vx := range this.Events {
		vy := that.Events[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &RushMaddenTimelineEvent{}
			}
			if q == nil {
				q = &RushMaddenTimelineEvent{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenTimelineState) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenTimelineState)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *RushMaddenTimelineEvent) EqualVT(that *RushMaddenTimelineEvent) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.TeamUrn != that.TeamUrn {
		return false
	}
	if this.EventType != that.EventType {
		return false
	}
	if !(*durationpb1.Duration)(this.RemainingTime).EqualVT((*durationpb1.Duration)(that.RemainingTime)) {
		return false
	}
	if this.Quarter != that.Quarter {
		return false
	}
	if this.Down != that.Down {
		return false
	}
	if !this.FirstDownDistance.EqualVT(that.FirstDownDistance) {
		return false
	}
	if this.YardsToEndzone != that.YardsToEndzone {
		return false
	}
	if this.PossessionSide != that.PossessionSide {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *RushMaddenTimelineEvent) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*RushMaddenTimelineEvent)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
